(lu-section)=
# LU decomposition

**LU decomposition** (also known as **LU factorisation**) is a procedure for decomposing a square matrix $A$ into the product of a lower triangular matrix $L$ and an upper triangular matrix $U$ such that

$$ A = LU. $$

The advantage of writing a matrix as a product of $L$ and $U$ is that the solution to a triangular set of equations is easy to calculate using forward or back substitution. Consider the LU decomposition of a $3\times 3$ matrix

$$ \begin{align*}
    \begin{pmatrix}
        a_{11}  & a_{12}  & a_{13} \\
        a_{21}  & a_{22}  & a_{32} \\
        a_{31}  & a_{32}  & a_{33} 
    \end{pmatrix}=
    \begin{pmatrix}
        \ell_{11}  & 0 & 0\\
        \ell_{21}  & \ell_{22}  & 0\\
        \ell_{31}  & \ell_{32}  & \ell_{33} 
    \end{pmatrix}\begin{pmatrix}
        u_{11}  & u_{12}  & u_{13} \\
        0 & u_{22}  & u_{23} \\
        0 & 0 & u_{33} 
    \end{pmatrix},
\end{align*} $$

which gives a system of 9 equations (one for each element in $A$) in 12 unknowns which has an infinite number of solutions. If we use the condition $\ell_{ii} = 1$ then[^1]

[^1]: Here we use $\ell$ instead of the lowercase character $l$ to avoid confusion with the uppercase character $I$ or the number 1.

$$ \begin{align*}
    \begin{pmatrix}
        a_{11}  & a_{12}  & a_{13} \\
        a_{21}  & a_{22}  & a_{23} \\
        a_{31}  & a_{32}  & a_{33} 
    \end{pmatrix}
    &=
    \begin{pmatrix}
        1 & 0 & 0 \\
        \ell_{21} & 1 & 0 \\
        \ell_{31} & \ell_{32} & 1 
    \end{pmatrix}
    \begin{pmatrix}
        u_{11} & u_{12} & u_{13} \\
        0 & u_{22} & u_{23} \\
        0 & 0 & u_{33}
    \end{pmatrix} \\
    &=
    \begin{pmatrix}
        u_{11}  & u_{12}  & u_{13} \\
        \ell_{21} u_{11}  & u_{22} + \ell_{21} u_{12}  & u_{23} + \ell_{21} u_{13} \\
        \ell_{31} u_{11}  & \ell_{31} u_{12} + \ell_{32} u_{22}  & u_{33} + \ell_{31} u_{13} +\ell_{32} u_{23}
    \end{pmatrix}.
\end{align*} $$

The elements in the lower triangular region, where $i>j$, are

$$ \begin{align*}
    a_{ij} =\sum_{k=1}^j \ell_{ik} u_{kj} =\ell_{ij} u_{jj} +\sum_{k=1}^{j-1} \ell_{ik} u_{kj}, 
\end{align*} $$

which is rearranged to

$$ \begin{align*}
    \ell_{ij} =\frac{1}{u_{jj} }\left(a_{ij} -\sum_{k=1}^{j-1} \ell_{ik} u_{kj} \right).
\end{align*} $$

For the elements in the upper triangular region where $i\le j$ we have

$$ \begin{align*}
    a_{ij} = u_{ij} +\sum_{k=1}^{i-1} \ell_{ik} u_{kj},
\end{align*} $$

which is rearranged to 

$$ \begin{align*}
    u_{ij} = a_{ij} -\sum_{k=1}^{i-1} \ell_{ik} u_{kj}.
\end{align*} $$

So to calculate an LU decomposition we loop through each column of $A$ and calculate the elements of $\ell_{ij}$ and $u_{ij}$ for that column.

```{prf:theorem} LU decomposition
:label: lu-theorem

The LU decomposition of an $n \times n$ square matrix $A$ results in two $n \times n$ matrices $L$ and $U$ such that $A = LU$. The elements of $L$ and $U$ are calculated using

$$ \begin{align*}
u_{ij} &= a_{ij} - \sum_{k=1}^{i-1} \ell_{ik}u_{kj}, & i &= 1, \ldots, j, \\
\ell_{ij} &= \dfrac{1}{u_{jj}} \left(a_{ij} - \displaystyle \sum_{k=1}^{j-1} \ell_{ik}u_{kj}\right), & i &= j+1, \ldots, n.
\end{align*} $$(lu-equation)
```

```{prf:algorithm} LU decomposition
:label: lu-algorithm

**Inputs:** A square $n \times n$ matrix $A$.

**Outputs:** Two square $n \times n$ matrices $L$ and $U$ such that $A = LU$.

- $L \gets I_n$
- $U \gets \vec{0}_{n \times n}$
- For each column $j$ in $A$ do
    - For each row $i$ in $A$ do
      - If $i \leq j$
          - $u_{ij} \gets a_{ij} - \displaystyle\sum_{k=1}^{i-1} \ell_{ik}u_{kj} $
      - Else
          - $\ell_{ij} \gets \dfrac{1}{u_{jj}} \left( a_{ij} - \displaystyle \sum_{k=1}^{j-1} \ell_{ik}u_{kj} \right)$
- Return $L$ and $U$
```

```{prf:example}
:class: seealso
:label: lu-example

Determine the LU decomposition of the following matrix

$$ A = \begin{pmatrix}
    2 & 3 & 1 \\
    -4 & -7 & 0 \\
    6 & 7 & 10
\end{pmatrix}.$$

---

**Solution**

We need to calculate the values of $\ell_{ij}$ and $u_{ij}$ such that

$$ \begin{align*}
  \begin{pmatrix}
      2 & 3 & 1 \\
      -4 & -7 & 0 \\
      6 & 7 & 10
  \end{pmatrix}
    &=
    \begin{pmatrix}
        1 & 0 & 0 \\
        \ell_{21} & 1 & 0 \\
        \ell_{31} & \ell_{32} & 1
    \end{pmatrix} 
    \begin{pmatrix} 
        u_{11} & u_{12} & u_{13} \\
        0 & u_{22} & u_{23} \\
        0 & 0 & u_{33}
    \end{pmatrix} \\
    &=
    \begin{pmatrix}
        u_{11} & u_{12} & u_{13} \\
        \ell_{21} u_{11} & \ell_{21} u_{12} + u_{22} & \ell_{21} u_{13}  + u_{23} \\
        \ell_{31} u_{11} & \ell_{31} u_{12} + \ell_{32} u_{22} & \ell_{31} u_{13} + \ell_{32} u_{23} + u_{33}
    \end{pmatrix}
\end{align*} $$

Solving for $\ell_{ij}$ and $u_{ij}$ column-by-column

$$ \begin{align*}
    j &= 1: & 2 &= u_{11} & \implies  u_{11} &= 2, \\
    &&-4 &= \ell_{21} u_{11} = 2\ell_{21} & \implies \ell_{21} &= -2, \\
    && 6 &= \ell_{31} u_{11} = 2\ell_{31} & \implies \ell_{31} &= 3,  \\
    j &= 2: & 3 &= u_{12} & \implies u_{12} &= 3, \\
    && -7 &= \ell_{21}u_{12} + u_{22} = -6 + u_{22} & \implies u_{22} &= -1, \\
    && 7 &= \ell_{31}u_{12} + \ell_{32}u_{22}= 9 - \ell_{32} & \implies \ell_{32} &= 2, \\
    j &= 3: & 1 &= u_{13} & \implies u_{13} &= 1, \\ 
    && 0 &= \ell_{21}u_{13} + u_{23} = -2 + u_{23} & \implies u_{23} &= 2, \\
    && 10 &= \ell_{31}u_{13} + \ell_{32}u_{23} + u_{33} = 3 + 4 + u_{33} & \implies u_{33} &= 3. 
\end{align*} $$

Therefore

$$ \begin{align*}
    L &= \begin{pmatrix}
        1 & 0 & 0\\
        -2 & 1 & 0\\
        3 & 2 & 1
    \end{pmatrix},&
    U &= \begin{pmatrix}
        2 & 3 & 1 \\
        0 & -1 & 2 \\
        0 & 0 & 3
    \end{pmatrix}.
\end{align*} $$

Checking that $LU=A$

$$ \begin{align*}
    \begin{pmatrix}
        1 & 0 & 0\\
        -2 & 1 & 0\\
        3 & 2 & 1
    \end{pmatrix}
    \begin{pmatrix}
        2 & 3 & 1 \\
        0 & -1 & 2 \\
        0 & 0 & 3
    \end{pmatrix} =
    \begin{pmatrix}
          2 & 3 & 1 \\
          -4 & -7 & 0 \\
          6 & 7 & 10
      \end{pmatrix}.
\end{align*} $$

```

## Code 

The code below defines a function called `lu()` which calculates the LU decomposition of a matrix.

`````{tab-set}
````{tab-item} Python
```python
def lu(A):
    n = A.shape[0]
    L, U = np.eye(n), np.zeros((n, n))
    
    for j in range(n):
        for i in range(j+1):
            sum_ = 0
            for k in range(i):
                sum_ += L[i,k] * U[k,j]
            
            U[i,j] = A[i,j] - sum_
        
        for i in range(j+1, n):
            sum_ = 0
            for k in range(i):
                sum_ += L[i,k] * U[k,j]

            L[i,j] = (A[i,j] - sum_) / U[j,j]
                
    return L, U
```
````

````{tab-item} MATLAB
```matlab
function [L, U] = lu(A)

n = size(A, 1);
L = eye(n);
U = zeros(n);

for j = 1 : n
    for i = 1 : j
        sum_ = 0;
        for k = 1 : i - 1
            sum_ = sum_ + L(i,k) * U(k,j);
        end
        U(i,j) = A(i,j) - sum_;
    end

    for i = j + 1 : n
        sum_ = 0;
        for k = 1 : i - 1
            sum_ = sum_ + L(i,k) * U(k,j);
        end
        L(i,j) = (A(i,j) - sum_) / U(j,j);
    end
end

end
```
````
`````

In [1]:
import numpy as np

def lu(A):
    n = A.shape[0]
    L, U = np.eye(n), np.zeros((n, n))
    
    for j in range(n):
        for i in range(j+1):
            sum_ = 0
            for k in range(i):
                sum_ += L[i,k] * U[k,j]
            
            U[i,j] = A[i,j] - sum_
        
        for i in range(j+1, n):
            sum_ = 0
            for k in range(i):
                sum_ += L[i,k] * U[k,j]

            L[i,j] = (A[i,j] - sum_) / U[j,j]
                
    return L, U


# Define matrix
A = np.array([[2, 3, 1],
              [-4, -7, 0],
              [6, 7, 10]])
b = np.array([-7, 11, 1])

# Calculate LU decomposition
L, U = lu(A)
print(f"L = \n{L}\n\nU = \n{U}")

L = 
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 3.  2.  1.]]

U = 
[[ 2.  3.  1.]
 [ 0. -1.  2.]
 [ 0.  0.  3.]]
