(lup-section)=

# LU Decomposition with Partial Pivoting

The formula for the elements of $L$ in {prf:ref}`LU decomposition<lu-theorem>`

$$ \begin{align*}
\ell_{ij} &= \dfrac{1}{u_{jj}} \left(a_{ij} - \displaystyle \sum_{k=1}^{j-1} \ell_{ik}u_{kj}\right),
\end{align*} $$

requires division by the pivot $u_{jj}$. If a pivot is zero, the LU decomposition cannot proceed. Even when the pivot is non-zero, a very small pivot can lead to large multipliers $\ell_{ij}$, making the computation sensitive to rounding errors. This can produce inaccurate solutions even when the exact solution is perfectly well behaved. 

For example, consider the linear system

$$ \begin{align*}
    \begin{pmatrix} 
        0.0001 & 1 \\ 
        1 & 1 
    \end{pmatrix}
    \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} &=
    \begin{pmatrix} 1 \\ 2 \end{pmatrix},
\end{align*}$$

which has the solution

$$ \begin{align*}
    x_1 &= \frac{10000}{9999} \approx 1.0001, &
    x_2 &= \frac{9998}{9999} \approx 0.9999.
\end{align*} $$

Calculating the LU decomposition of the coefficient matrix

$$ \begin{align*}
    u_{11} &= a_{11} = 0.0001, \\
    \ell_{21} &= \frac{1}{u_{11}}a_{21} = \frac{1}{0.0001}(1) = 10000, \\
    u_{12} &= a_{12} = 1, \\
    u_{22} &= - \ell_{21} u_{12} = 1 - 10000(1) = -9999,
\end{align*} $$

therefore

$$ \begin{align*}
    L &= \begin{pmatrix} 
        1 & 0 \\
        10000 & 1 
    \end{pmatrix}, &
    U &= \begin{pmatrix} 
        0.0001 & 1 \\
        0 & -9999
    \end{pmatrix},
\end{align*} $$

To illustrate the effect of finite-precision arithmetic, suppose all calculations are rounded to three decimal places at each stage. Solving $L\mathbf{y} = \mathbf{b}$ by forward substitution

$$ \begin{align*}
    \begin{pmatrix} 
        1 & 0 \\
        10000 & 1 
    \end{pmatrix}
    \begin{pmatrix} y_1 \\ y_2 \end{pmatrix} &=
    \begin{pmatrix} 1 \\ 2 \end{pmatrix} 
    \quad \implies \quad
    \begin{aligned} y_1 &= 1 \\ y_2 &= 2 - 10000(1) = -9998, \end{aligned}
\end{align*} $$

and solving $U \mathbf{x} = \mathbf{y}$ by back substitution

$$ \begin{align*}
    \begin{pmatrix} 
        0.0001 & 1 \\
        0 & -9999
    \end{pmatrix}
    \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} &= 
    \begin{pmatrix} 1 \\ -9998 \end{pmatrix}
    \quad \implies \quad
    \begin{aligned} 
        x_2 &= \frac{-9998}{-9999} \approx 1.000 \\ 
        x_1 &\approx \frac{1}{0.0001}(1 - 1) = 0.
    \end{aligned}
\end{align*} $$

So we have a computed solution $x_1 = 0$ whereas the exact solution is $x_1 \approx 1$. In partial pivoting, the current pivot is chosen to be the entry with the largest absolute value in the current column among the rows that have not yet been eliminated. This is achieved by swapping rows before the elimination step.

$$ \begin{align*}
    \begin{pmatrix} 
        1 & 1 \\
        0.0001 & 1 
    \end{pmatrix}
    \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} &=
    \begin{pmatrix} 2 \\ 1 \end{pmatrix}.
\end{align*}$$

Calculating the LU decomposition of the coefficient matrix

$$ \begin{align*}
    u_{11} &= a_{11} = 1, \\
    \ell_{21} &= \frac{1}{u_{11}}a_{21} = 0.0001, \\
    u_{12} &= a_{12} = 1, \\
    u_{22} &= a_{22} - \ell_{21}u_{12} = 1 - 0.0001(1) = 0.9999
\end{align*} $$ 

therefore

$$ \begin{align*}
    L &= \begin{pmatrix} 
        1 & 0 \\
        0.0001 & 1 
    \end{pmatrix}, &
    U &= \begin{pmatrix} 
        1 & 1 \\
        0 & 0.9999
    \end{pmatrix}.
\end{align*} $$

Solving $L \mathbf{y} = \mathbf{b}$ using the same precision as before

$$ \begin{align*}
    \begin{pmatrix} 
        1 & 0 \\
        0.0001 & 1 
    \end{pmatrix}
    \begin{pmatrix} y_1 \\ y_2 \end{pmatrix} &=
    \begin{pmatrix} 2 \\ 1 \end{pmatrix}
    \quad \implies \quad
    \begin{aligned} 
        y_1 &= 2, \\
        y_2 &= 1 - 0.0001(2) \approx 1, 
    \end{aligned}
\end{align*} $$

Solving $U \mathbf{x} = \mathbf{y}$

$$ \begin{align*}
    \begin{pmatrix} 
        1 & 1 \\
        0 & 0.9999
    \end{pmatrix}
    \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} &= 
    \begin{pmatrix} 2 \\ 0.9998 \end{pmatrix} 
    \quad \implies \quad
    \begin{aligned}
        x_2 &= \frac{0.9998}{0.9999} \approx 1, \\
        x_1 &\approx 2 - 1 = 1.
    \end{aligned}
\end{align*} $$

Now we have the solution $x_1 \approx 1$ and $x_2 \approx 1$ which is closer to the exact solution of $x_1 \approx 1.0001$ and $x_2 \approx 0.9999$. Note that swapping rows of the coefficient matrix does not change the solution to the system as long as the same swap is applied to the constant vector. 

In practice, partial pivoting is performed automatically during Gaussian elimination and LU decomposition because it usually improves numerical stability and avoids division by zero.

```{prf:definition} Partial pivoting
At the $k$-th step of Gaussian elimination, partial pivoting selects as the pivot the entry with the largest absolute values in column $k$ among rows $k, k+1, \ldots, n$. If this entry is not already in row $k$, the corresponding rows are swapped before elimination proceeds. 
```

Formally, for column $k$, we choose the row $p$ such that

$$ |a_{pk}| = \max_{i=k, \ldots, n} |a_{ik}|. $$

Rows $k$ and $p$ are then swapped. These row swaps can be represented using a **permutation matrix** $P$. A permutation matrix is obtained by performing the same row swaps on the identity matrix as are applied to $A$. The matrix $PA$ is the matrix obtained after performing all row swaps determined by partial pivoting. 

```{prf:example}
:label: pivoting-example

Apply partial pivoting to the following matrix and determine the permutation matrix $P$

$$ A =\begin{pmatrix}
        0 & 1 & -2\\
        1 & 0 & 2\\
        3 & -2 & 2
    \end{pmatrix}. $$

---

**Solution**

Applying partial pivoting to $A$

$$ \begin{align*}
    &\begin{pmatrix}
        0 & 1 & -2\\
        1 & 0 & 2\\
        3 & -2 & 2
    \end{pmatrix}
    \begin{array}{l} R_1 \leftrightarrow R_3 \\ \phantom{x} \\ \phantom{x} \end{array}
    \longrightarrow 
    &\begin{pmatrix}
        3 & -2 & 2\\
        1 & 0 & 2\\
        0 & 1 & -2
    \end{pmatrix}
    \begin{array}{l} \\ R_2 \leftrightarrow R_3 \\ \phantom{x} \end{array}\\ \\
    \longrightarrow 
    &\begin{pmatrix}
        3 & -2 & 2\\
        0 & 1 & -2\\
        1 & 0 & 2
    \end{pmatrix}
    \begin{array}{l} \\ R_2 \leftrightarrow R_3 \\ \phantom{x} \end{array}
\end{align*} $$

Performing the same row operations on the identity matrix
   
$$ \begin{align*}
    &\begin{pmatrix}
        1 & 0 & 0\\
        0 & 1 & 0\\
        0 & 0 & 1
    \end{pmatrix}
    \begin{array}{l} R_1 \leftrightarrow R_3 \\ \phantom{x} \\ \phantom{x} \end{array}
    \longrightarrow 
    &\begin{pmatrix}
        0 & 0 & 1\\
        0 & 1 & 0\\
        1 & 0 & 0
    \end{pmatrix}
    \begin{array}{l} \\ R_2 \leftrightarrow R_3 \\ \phantom{x} \end{array}\\ \\
    \longrightarrow 
    &\begin{pmatrix}
        0 & 0 & 1\\
        1 & 0 & 0\\
        0 & 1 & 0
    \end{pmatrix}
\end{align*} $$

Therefore, the permutation matrix is

$$ P = \begin{pmatrix}
        0 & 0 & 1\\
        1 & 0 & 0\\
        0 & 1 & 0
    \end{pmatrix} $$
```

---

(lup-decomposition-section)=

## LUP decomposition

The standard form of an LU decomposition with partial pivoting is

$$ PA = LU, $$

where $P$ is a permutation matrix. Since partial pivoting consists of row swaps, the same row swaps must be applied to both sides of the system

$$A \mathbf{x} = \mathbf{b}.$$

Pre-multiplying by $P$ gives

$$ P A \mathbf{x} = P \mathbf{b}. $$

Using the factorisation  $PA = LU$, we obtain

$$ LU \mathbf{x} = P \mathbf{b}. $$

Introducing an intermediate vector $\mathbf{y}$ such that

$$ U \mathbf{x} = \mathbf{y}, $$

the system becomes

$$ L \mathbf{y} = P \mathbf{b}. $$

Since $L$ is lower triangular, $\mathbf{y}$ is computed using forward substitution. Once $\mathbf{y}$ has been determined, the solution vector $\mathbf{x}$ is obtained by solving

$$ U\mathbf{x}=\mathbf{y}, $$

using back substitution.

```{prf:algorithm} Solving system of linear equations using LU decomposition with partial pivoting
:label: lup-algorithm

**Inputs:** A system of linear equations expressed using the coefficient matrix $A$ and variable vector $\mathbf{b}$ such that $A \mathbf{x} = \mathbf{b}$.

**Outputs:** The solution vector $\mathbf{x}$.

- Perform partial pivoting on $A$ and determine the permutation matrix $P$
- Calculate the LU decomposition of $PA$
- $\mathbf{b} \gets P \mathbf{b}$
- for $i = 1, \ldots, n$ do
  - $y_i \gets b_i - \displaystyle\sum_{j=1}^{i - 1} \ell_{ij} y_j$
- $x_n \gets \dfrac{y_n}{u_{nn}}$
- for $i = n - 1, \ldots, 1$ do
  - $x_i \gets \dfrac{1}{u_{ii}} \left( y_i - \displaystyle \sum_{j=i+1}^{n} u_{ij} x_j \right)$
- Return $\mathbf{x}$.
```

```{prf:example}
:label: lup-example

Solve the following system of linear equations using LU decomposition with partial pivoting

$$ \begin{align*}
    \begin{pmatrix}
        0 & 1 & -2\\
        1 & 0 & 2\\
        3 & -2 & 2
    \end{pmatrix}
    \begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix} =
    \begin{pmatrix} 10 \\ -4 \\ -8 \end{pmatrix}.
\end{align*} $$

---

**Solution**

We have seen from the {prf:ref}`pivoting-example` that applying partial pivoting to the coefficient matrix results in

$$ \begin{align*}
    P &= \begin{pmatrix}
        0 & 0 & 1\\
        1 & 0 & 0\\
        0 & 1 & 0
    \end{pmatrix}, &
    PA &= \begin{pmatrix}
        3 & -2 & 2\\
        0 & 1 & -2\\
        1 & 0 & 2
    \end{pmatrix}, &
\end{align*} $$

Calculating the LU decomposition of $PA$ 

$$ \begin{align*}
    j &= 1: & u_{11} &= a_{11} = 3, \\
    && \ell_{21} &= \frac{1}{u_{11}} a_{21} = \frac{1}{3}(0) = 0, \\
    && \ell_{31} &= \frac{1}{u_{11}} a_{31} = \frac{1}{3}(1) = \frac{1}{3}, \\
    j &= 2: & u_{12} &= a_{12} = -2, \\
    && u_{22} &= a_{22} - \ell_{21}u_{12} = 1 - 0(-2) = 1, \\
    && \ell_{32} &= \frac{1}{u_{22}}(a_{32} - \ell_{31}u_{12}) = \frac{1}{1}\left(0 - \frac{1}{3}(-2)\right) = \frac{2}{3}, \\
    j &= 3: & u_{13} &= a_{13} = 2, \\
    && u_{23} &= a_{23} - \ell_{21}u_{13} = -2 - 0(2) = -2, \\
    && u_{33} &= a_{33} - \ell_{31}u_{13} - \ell_{32}u_{23} = 2 - \frac{1}{3}(2) - \frac{2}{3}(-2) = \frac{8}{3}, 
\end{align*} $$

therefore

$$ \begin{align*}
    L &= \begin{pmatrix}
        1 & 0 & 0\\
        0 & 1 & 0\\
        \frac{1}{3} & \frac{2}{3} & 1
    \end{pmatrix}, &
    U &= \begin{pmatrix}
        3 & -2 & 2\\
        0 & 1 & -2\\
        0 & 0 & \frac{8}{3}
    \end{pmatrix}.
\end{align*} $$

Solving $L \mathbf{y} = P \mathbf{b}$ using forward substitution 

$$ \begin{align*}
    \begin{pmatrix}
        1 & 0 & 0\\
        0 & 1 & 0\\
        \frac{1}{3} & \frac{2}{3} & 1
    \end{pmatrix}
    \begin{pmatrix} y_1 \\ y_2 \\ y_3 \end{pmatrix} =
    \begin{pmatrix}
        0 & 0 & 1\\
        1 & 0 & 0\\
        0 & 1 & 0
    \end{pmatrix}
    \begin{pmatrix} 10 \\ -4 \\ -8 \end{pmatrix} =
    \begin{pmatrix} -8 \\ 10 \\ -4 \end{pmatrix},
\end{align*} $$

gives

$$ \begin{align*}
    y_1 &= -8, \\
    y_2 &= 10 - 0(8)=10, \\
    y_3 &= -4 - \frac{1}{3}(-8) + \frac{2}{3}(10) = -8.
\end{align*} $$

Solving $U \mathbf{x} = \mathbf{y}$ using back substitution

$$ \begin{align*}
    \begin{pmatrix}
        3 & -2 & 2\\
        0 & 1 & -2\\
        0 & 0 & 8/3
    \end{pmatrix}
    \begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix} = 
    \begin{pmatrix} -8 \\ 10 \\ -8 \end{pmatrix},
\end{align*} $$

gives

$$ \begin{align*}
    x_3 &= \frac{3}{8}(-8) = -3, \\
    x_2 &= \frac{1}{1}(10+2(-3)) = 4, \\
    x_1 &= \frac{1}{3}(-8+2(4)-2(-3)) = 2.
\end{align*} $$

So the solution is $\mathbf{x}=(2,4,-3)$.

```

In [1]:
import numpy as np

def lu(A):
    n = A.shape[0]
    L, U = np.eye(n), np.zeros((n, n))
    
    for j in range(n):
        for i in range(j+1):
            sum_ = 0
            for k in range(i):
                sum_ += L[i,k] * U[k,j]
            
            U[i,j] = A[i,j] - sum_
        
        for i in range(j+1, n):
            sum_ = 0
            for k in range(i):
                sum_ += L[i,k] * U[k,j]

            L[i,j] = (A[i,j] - sum_) / U[j,j]
                
    return L, U


def forward_substitution(L, b):
    n = L.shape[0]
    x = np.zeros(n)
    for i in range(n):
        sum_ = 0
        for j in range(i):
            sum_ += L[i,j] * x[j]
            
        x[i] = (b[i] - sum_) / L[i,i]
    
    return x


def back_substitution(U, b):
    n = U.shape[0]
    x = np.zeros(n)
    x[-1] = b[-1] / U[-1,-1]
    for i in range(n - 2, -1, -1):
        sum_ = 0
        for j in range(i + 1, n):
            sum_ += U[i,j] * x[j]
            
        x[i] = (b[i] - sum_) / U[i,i]
        
    return x


def partial_pivot(A):
    n = A.shape[0]
    P = np.eye(n)
    for j in range(n):
        maxpivot, maxpivotrow = A[j,j], j
        for i in range(j + 1, n):
            if A[i,j] > maxpivot:
                maxpivot, maxpivotrow = A[i,j], i

        A[[j,maxpivotrow]] = A[[maxpivotrow,j]] 
        P[[j,maxpivotrow]] = P[[maxpivotrow,j]]

    return P


# Define linear system
A = np.array([[0, 1, -2],
              [1, 0, 2],
              [3, -2, 2]])
b = np.array([10, -4, -8])

# Calculate LUP decomposition
P = partial_pivot(A)
L, U = lu(A)
print(f"L = \n{L},\n\nU = \n{U},\n\nP = \n{P}")

# Solve linear system
y = forward_substitution(L, np.dot(P, b))
x = back_substitution(U, y)
print(f"\nx = {x}")

L = 
[[1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.33333333 0.66666667 1.        ]],

U = 
[[ 3.         -2.          2.        ]
 [ 0.          1.         -2.        ]
 [ 0.          0.          2.66666667]],

P = 
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]

x = [ 2.  4. -3.]
