(matrix-decomposition-exercises-section)=

# Matrix decomposition exercises

`````{exercise}
:label: matrix-decomposition-ex-lu

Using pen and paper, solve the following system of linear equations using {prf:ref}`LU decomposition<lu-theorem>`.

$$\begin{align*}
    2 x_1 + 3 x_2 -   x_3   &=  4,\\
    4 x_1 + 9 x_2 -   x_3   &= 18,\\
            3 x_2 + 2 x_3 &= 11.
\end{align*} $$

<!-- ````{grid}
```{grid-item}
:columns: 6
(a) &emsp;
$ \begin{align*}
    2 x_1 + 3 x_2 -   x_3   &=  4,\\
    4 x_1 + 9 x_2 -   x_3   &= 18,\\
            3 x_2 + 2 x_3 &= 11.
\end{align*} $
```

```{grid-item}
:columns: 6 
(b) &emsp;
$ \begin{align*}
    3 x_1 + 9 x_2 + 5 x_3 &= 20,\\
      x_1 + 2 x_2 + 2 x_3 &=  3,\\
    2 x_1 + 4 x_2 + 5 x_3 &=  4.
\end{align*} $
```

```{grid-item}
:columns: 6
<br>

(c)  &emsp;
$ \begin{align*}
      x_1         + 3 x_3 + 2 x_4 &=  21,\\
    3 x_1 - 2 x_2 + 5 x_3 +   x_4 &=  28,\\
    4 x_1 -   x_2 - 2 x_3 - 3 x_4 &= -12,\\
            2 x_2         + 3 x_4 &=  13.
\end{align*} $
```

```{grid-item}
:columns: 6
<br>

(d) &emsp;
$ \begin{align*}
        x_1 + 5 x_2 + 2 x_3 + 2 x_4 &= -10,\\
    - 2 x_1 - 4 x_2 + 2 x_3         &=  10,\\
      3 x_1 +   x_2 - 2 x_3 -   x_4 &= -2,\\
    - 3 x_1 - 3 x_2 + 4 x_3 -   x_4 &=  4.
\end{align*} $
```
```` -->

```{dropdown} Solution
$$ \begin{align*}
  L &= \begin{pmatrix}
    1 & 0 & 0 \\
    2 & 1 & 0 \\
    0 & 1 & 1
  \end{pmatrix}, &
  U &= \begin{pmatrix}
    2 & 3 & -1 \\
    0 & 3 & 1 \\
    0 & 0 & 1
  \end{pmatrix}, &
  \mathbf{x} &= \begin{pmatrix} -2 \\ 3 \\ 1 \end{pmatrix}
\end{align*} $$
```
`````


In [1]:
import numpy as np

def lu(A):
    n = A.shape[0]
    L, U = np.eye(n), np.zeros((n, n))
    for j in range(n):
        for i in range(n):
            sum_ = 0
            if i <= j:
                for k in range(i):
                    sum_ += L[i,k] * U[k,j]
        
                U[i,j] = A[i,j] - sum_   
            
            else:         
                for k in range(j):
                    sum_ += L[i,k] * U[k,j]
                    
                L[i,j] = (A[i,j] - sum_) / U[j,j]
    
    return L, U

# (a)
A = np.array([[2, 3, -1], [4, 9, -1], [0, 3, 2]])
b = np.array([4, 18, 11])
L, U = lu(A)

print('(a)')
print(f'L = {L}')
print(f'\nU = {U}')
print(f'\nx = {np.linalg.solve(A, b)}')

# (b)
A = np.array([[3, 9, 5], [1, 2, 2], [2, 4, 5]])
b = np.array([20, 3, 4])
L, U = lu(A)

print('\n(b)')
print(f'L = {L}')
print(f'\nU = {U}')
print(f'\nx = {np.linalg.solve(A, b)}')

# (c)
A = np.array([[1, 0, 3, 2], [3, -2, 5, 1], [4, -1, -2, -3], [0, 2, 0, 3]])
b = np.array([21, 28, -12, 13])
L, U = lu(A)

print('\n(c)')
print(f'L = {L}')
print(f'\nU = {U}')
print(f'\nx = {np.linalg.solve(A, b)}')

# (d)
A = np.array([[1, 5, 2, 2], [-2, -4, 2, 0], [3, 1, -2, -1], [-3, -3, 4, -1]])
b = np.array([-10, 10, -2, 4])
L, U = lu(A)

print('\n(d)')
print(f'L = {L}')
print(f'\nU = {U}')
print(f'\nx = {np.linalg.solve(A, b)}')


(a)
L = [[1. 0. 0.]
 [2. 1. 0.]
 [0. 1. 1.]]

U = [[ 2.  3. -1.]
 [ 0.  3.  1.]
 [ 0.  0.  1.]]

x = [-2.  3.  1.]

(b)
L = [[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.66666667 2.         1.        ]]

U = [[ 3.          9.          5.        ]
 [ 0.         -1.          0.33333333]
 [ 0.          0.          1.        ]]

x = [ 1.  3. -2.]

(c)
L = [[ 1.          0.          0.          0.        ]
 [ 3.          1.          0.          0.        ]
 [ 4.          0.5         1.          0.        ]
 [ 0.         -1.          0.33333333  1.        ]]

U = [[  1.           0.           3.           2.        ]
 [  0.          -2.          -4.          -5.        ]
 [  0.           0.         -12.          -8.5       ]
 [  0.           0.           0.           0.83333333]]

x = [ 2. -1.  3.  5.]

(d)
L = [[ 1.          0.          0.          0.        ]
 [-2.          1.          0.          0.        ]
 [ 3.         -2.33333333  1.          0.        ]


````{exercise}
:label: matrix-decomposition-ex-lup

Using pen and paper, solve the following system of linear equations using [LU decomposition with partial pivoting](lup-section).

$$ $ \begin{align*}
    3 x_2 + 2 x_3 &= 11, \\
    4 x_1 + 9 x_2 -   x_3   &= 18,\\
    2 x_1 + 3 x_2 -   x_3   &=  4.
\end{align*} $$
````



`````{exercise}
:label: matrix-decomposition-ex-cholesky

Using pen and paper, solve the following systems of linear equations using [Cholesky decomposition](cholesky-section).

````{grid}
```{grid-item}
:columns: 6
(a) &emsp; $ \begin{align*}
    16x_1 +16x_2 +4x_3 &=-8,\\
    16x_1 +25x_2 +10x_3 &=-47,\\
    4x_1 +10x_2 +6x_3 &=-30.
\end{align*} $
```

```{grid-item}
:columns: 6
(b) &emsp;
$ \begin{align*}
    4x_1 +2x_2 +8x_3 &=36,\\
    2x_1 +17x_2 +20x_3 &=50,\\
    8x_1 +20x_2 +41x_3 &=122.
\end{align*} $
```

```{grid-item}
<br>

(c) &emsp; 
$ \begin{align*}
    9x_1 -9x_2 -6x_4 &=12,\\
    -9x_1 +25x_2 +8x_3 -10x_4 &=-116,\\
    8x_2 +8x_3 -2x_4 &=-58,\\
    -6x_1 -10x_2 -2x_3 +33x_4 &=91.
\end{align*} $
```
````
`````

```{exercise}
:label: matrix-decomposition-ex-qr-gramschmidt

Using pen and paper, calculate the QR decomposition using the [Gram-Schmidt process](qr-gramschmidt-section) of the following matrices:

(a) &emsp; $ \begin{pmatrix} 1 & 1 \\  -1 & 0 \end{pmatrix}$;

(b) &emsp; $\begin{pmatrix} 6 & 6 & 1 \\ 3 & 6 & 1 \\ 2 & 1 & 1 \end{pmatrix}$;

(c) &emsp; $\begin{pmatrix} 1 & 2 & 1 \\ 1 & 4 & 3 \\ 1 & -4 & 6 \\ 1 & 2 & 1 \end{pmatrix}$.
```

```{exercise}
:label: matrix-decomposition-ex-qr-householder

Using pen and paper, calculate the QR decomposition using the [Householder transformations](qr-householder-section) of the following matrices:

(a) &emsp; $ \begin{pmatrix} 3 & 0 \\  4 & 5 \end{pmatrix}$;

(b) &emsp; $\begin{pmatrix} 1 & 2 & 4 \\ 0 & 0 & 5 \\ 0 & 3 & 6 \end{pmatrix}$;

(c) &emsp; $\begin{pmatrix} 2 & -2 & 18 \\ 2 & 1 & 0 \\ 1 & 2 & 0 \end{pmatrix}$.
```
