(cholesky-section)=
# Cholesky decomposition

**Cholesky decomposition** is an efficient matrix decomposition method that can be used when a square matrix is **positive definite**.

```{prf:definition} Positive definite matrix
:label: positive-definite-definition

A square matrix $A$ is said to be positive definite if

$$ \mathbf{x}^\mathsf{T} A \mathbf{x} > 0, $$

for all $\mathbf{x} \in \mathbb{R}^n \backslash \{\mathbf{0}\}$.
```

```{prf:theorem} Determinant test for a positive definite matrix
:label: determinant-test-for-positive-definite-matrix-theorem

A square matrix $A$ is positive definite if it is symmetric and the determinants of all $k \times k$ upper-left sub-matrices are all positive.
```

```{prf:example}
:label: positive-definite-example

Use the determinant test to show that the following matrix is positive definite

$$ \begin{align*}
    A = \begin{pmatrix}
        2 & -1 & 0 \\
        -1 & 2 & -1 \\
        0 & -1 & 2
    \end{pmatrix}.
\end{align*} $$

---

**Solution**

Matrix $A$ is symmetric since $A=A^\mathsf{T}$. Checking the determinants of the upper-left sub-matrices

$$ \begin{align*}
    \det(2) &= 2 > 0, \\
    \det\begin{pmatrix} 2 & -1 \\ -1 & 2 \end{pmatrix} &= 4 - 1 = 3 > 0, \\
    \det\begin{pmatrix}
        2 & -1 & 0 \\
        -1 & 2 & -1 \\
        0 & -1 & 2
    \end{pmatrix}
    &= 6 - 2 + 0 = 4 > 0 .
\end{align*} $$

Since $A$ is a symmetric matrix and all the determinants of the upper-left sub-matrices are positive then $A$ is a positive definite matrix.
```

Given a positive definite matrix $A$ the Cholesky decomposition decomposes $A$ into the product of a lower triangular matrix $L$ and its transpose $L^\mathsf{T}$, i.e.,

$$ \begin{align*}
    A = LL^\mathsf{T}.
\end{align*} $$

Consider the Cholesky decomposition of a $3\times 3$ matrix

$$ \begin{align*}
    \begin{pmatrix}
        a_{11}  & a_{12}  & a_{13} \\
        a_{21}  & a_{22}  & a_{23} \\
        a_{31}  & a_{32}  & a_{33} 
    \end{pmatrix} &= 
    \begin{pmatrix}
        \ell_{11}  & 0 & 0 \\
        \ell_{21}  & \ell_{22}  & 0 \\
        \ell_{31}  & \ell_{32}  & \ell_{33} 
    \end{pmatrix}
    \begin{pmatrix}
        \ell_{11}  & \ell_{21}  & \ell_{31} \\
        0 & \ell_{22}  & \ell_{32} \\
        0 & 0 & \ell_{33} 
    \end{pmatrix}\\
    &= 
    \begin{pmatrix}
        \ell_{11}^2  & \ell_{11} \ell_{21}  & \ell_{11} \ell_{31} \\
        \ell_{11} \ell_{21}  & \ell_{21}^2 +\ell_{22}^2  & \ell_{21} \ell_{31} +\ell_{22} \ell_{33} \\
        \ell_{11} \ell_{31}  & \ell_{21} \ell_{31} +\ell_{22} \ell_{33}  & \ell_{31}^2 +\ell_{32}^2 +\ell_{33}^2 
    \end{pmatrix}.
\end{align*} $$

The elements on the main diagonal are

$$ \begin{align*}
    a_{jj} =\ell_{jj}^2 +\sum_{k=1}^{j-1} \ell_{jk}^2 ,
\end{align*} $$

and the other elements are

$$ \begin{align*}
    a_{ij} =\sum_{k=1}^j \ell_{ik} \ell_{jk} = \ell_{jj} \ell_{ij} +\sum_{k=1}^{j-1} \ell_{ik} \ell_{jk}.
\end{align*} $$

Rearranging these expressions gives the following definition

```{prf:theorem} Cholesky decomposition
:label: cholesky-theorem

The Cholesky decomposition of an $n \times n$ positive definite matrix $A$ results in an $n \times n$ matrix $L$ such that $A = LL^\mathsf{T}$. The elements of $L$ are calculated using

$$ \begin{align}
    \ell_{jj} &= \sqrt{a_{jj} - \sum_{k=1}^{j-1} \ell_{jk}^2 }, & j &= 1, \ldots, n,\\
    \ell_{ij} &= \dfrac{1}{\ell_{jj} }\left(a_{ij} -\displaystyle \sum_{k=1}^{j-1} \ell_{ik} \ell_{jk} \right), & i &= j + 1,\ldots ,n.
\end{align} $$(cholesky-equation)
```

```{prf:algorithm} Cholesky decomposition
:label: cholesky-algorithm

**Inputs:** An $n \times n$ positive definite matrix $A$.

**Outputs:** An $n \times n$ lower triangular matrix $L$ such that $A = LL^\mathsf{T}$. 

- $L \gets \mathbf{0}_{n \times n}$
- For $j = 1, \ldots n$ do
  - $\ell_{jj} \gets \sqrt{a_{jj} - \displaystyle\sum_{k=1}^{j-1} \ell_{jk}^2}$
  - For $i = j + 1, \ldots n$ do 
    - $\ell_{ij} \gets \dfrac{1}{\ell_{jj} }\left(a_{ij} -\displaystyle \sum_{k=1}^{j-1} \ell_{ik} \ell_{jk} \right)$
- Return $L$
```

```{prf:example}
:label: cholesky-example

Calculate the Cholesky decomposition of the following matrix

$$ \begin{align*}
    A = \begin{pmatrix}
        4 & -2 & -4\\
        -2 & 10 & 5\\
        -4 & 5 & 14
    \end{pmatrix}.
\end{align*} $$

---

**Solution**

We need to solve $A = LL^\mathsf{T}$ for $\ell_{ij}$, i.e.,

$$ \begin{align*}
    \begin{pmatrix}
        4 & -2 & -4\\
        -2 & 10 & 5\\
        -4 & 5 & 14
    \end{pmatrix}
    &=
    \begin{pmatrix}
        \ell_{11} & 0 & 0 \\
        \ell_{21} & \ell_{22} & 0 \\
        \ell_{31} & \ell_{32} & \ell_{33}
    \end{pmatrix}
    \begin{pmatrix}
        \ell_{11} & \ell_{21} & \ell_{31} \\
        0 & \ell_{22} & \ell_{32} \\
        0 & 0 & \ell_{33} 
    \end{pmatrix} \\
    &=
    \begin{pmatrix}
        \ell_{11}^2 & \ell_{11} \ell_{21} & \ell_{11} \ell_{31} \\
        \ell_{21} \ell_{11} & \ell_{21}^2 + \ell_{22}^2 & \ell_{21} \ell_{31} + \ell_{22} \ell_{32} \\
        \ell_{31}\ell_{11} & \ell_{31} \ell_{21} + \ell_{32} \ell_{22} & \ell_{31}^2 + \ell_{32}^2 + \ell_{33}^2
    \end{pmatrix}.
\end{align*} $$

Note that $LL^\mathsf{T}$ is symmetric so we only need to calculate the lower triangular elements.

$$ \begin{align*}
    j &= 1: & 4 &= \ell_{11}^2 & \implies \ell_{11} &= 2, \\
    && -2 &= \ell_{21} \ell_{11} = 2\ell_{21} & \implies \ell_{21} &= -1, \\
    && -4 &= \ell_{31} \ell_{11} = 2\ell_{31} & \implies \ell_{31} &= -2, \\
    j &= 2: & 10 &= \ell_{21}^2 + \ell_{22}^2 = 1 + \ell_{22}^2 & \implies \ell_{22} &= 3, \\
    && 5 &= \ell_{31} \ell_{21} + \ell_{32} \ell_{22} = 2 + 3\ell_{32} & \implies \ell_{32} &= 1, \\
    j &= 3: & 14 &= \ell_{31}^2 + \ell_{32}^2 + \ell_{33}^2 = 4 + 1 + \ell_{33}^2 & \implies \ell_{33} &= 3,
\end{align*} $$

therefore

$L=\begin{pmatrix} 2 & 0 & 0 \\ -1 & 3 & 0 \\ -2 & 1 & 3 \end{pmatrix}$. Checking that $A = LL^\mathsf{T}$

$$ \begin{align*}
    \begin{pmatrix}
        2 & 0 & 0\\
        -1 & 3 & 0\\
        -2 & 1 & 3
    \end{pmatrix}
    \begin{pmatrix}
        2 & -1 & -2\\
        0 & 3 & 1\\
        0 & 0 & 3
    \end{pmatrix} =
    \begin{pmatrix}
        4 & -2 & -4\\
        -2 & 10 & 5\\
        -4 & 5 & 14
    \end{pmatrix}.
\end{align*} $$
```

## Code

The code below defines a function called `lu()` that calculates the Cholesky decomposition of a positive-definite matrix. This is used to calculate the Cholesky decompostiion of the matrix from {prf:ref}`cholesky-example`.

`````{tab-set}
````{tab-item} Python
```python
def cholesky(A):
    n = A.shape[0]
    L = np.zeros((n, n))   
    for j in range(n):
        sum_ = 0
        for k in range(j):
            sum_ += L[j,k] ** 2
        
        L[j,j] = np.sqrt(A[j,j] - sum_)
                
        for i in range(j+1, n):
            sum_ = 0
            for k in range(j):
                sum_ += L[i,k] * L[j,k]
            
            L[i,j] = (A[i,j] - sum_) / L[j,j]
    
    return L
```
````

````{tab-item} MATLAB
```matlab
function L = cholesky(A)

n = size(A, 1);
L = zeros(n);

for j = 1 : n
    sum_ = 0;
    for k = 1 : j - 1
        sum_ = sum_ + L(j,k) ^ 2;
    end
    L(j,j) = sqrt(A(j,j) - sum_);

    for i = j + 1 : n
        sum_ = 0;
        for k = 1 : j - 1
            sum_ = sum_ + L(i,k) * L(j,k);
        end
        L(i,j) = (A(i,j) - sum_) / L(j,j);
    end
end

end
```
````
`````

In [1]:
import numpy as np

def cholesky(A):
    n = A.shape[0]
    L = np.zeros((n, n))   
    for j in range(n):
        sum_ = 0
        for k in range(j):
            sum_ += L[j,k] ** 2
        
        L[j,j] = np.sqrt(A[j,j] - sum_)
                
        for i in range(j+1, n):
            sum_ = 0
            for k in range(j):
                sum_ += L[i,k] * L[j,k]
            
            L[i,j] = (A[i,j] - sum_) / L[j,j]
    
    return L


# Define matrix
A = np.array([[4, -2, -4], 
              [-2, 10, 5], 
              [-4, 5, 14]])

# Calculate Cholesky decomposition
L = cholesky(A)
print(f"L = \n{L}\n")

L = 
[[ 2.  0.  0.]
 [-1.  3.  0.]
 [-2.  1.  3.]]



## Solving systems of linear equations using Cholesky decomposition

Given a system of linear equations of the form $A \mathbf{x} = \mathbf{b}$ where Cholesky decomposition has been applied to the coefficient matrix then since $A = LL^\mathsf{T}$ we have

$$ LL^\mathsf{T} \mathbf{x} = \mathbf{b}.$$

Let $\mathbf{y} = L^\mathsf{T} \mathbf{x}$ then

$$ L \mathbf{y} = \mathbf{b}. $$

Similar to solving systems using [LU decomposition](solving-systems-using-lu-section) we solve $L \mathbf{y} = \mathbf{b}$ for $\mathbf{y}$ using forward substitution and then $L^\mathsf{T} \mathbf{x} = \mathbf{y}$ using back substitution.

```{prf:algorithm} Solving systems of linear equations using Cholesky decomposition
:label: cholesky-solution-algorithm

**Inputs:** A system of linear equations expressed using the coefficient matrix $A$ and variable vector $\mathbf{b}$ such that $A \mathbf{x} = \mathbf{b}$.

**Inputs:** The variable vector $\mathbf{x}$.

- Calculate the {prf:ref}`Cholesky decomposition<cholesky-algorithm>` of $A$ to determine $L$ such that $A = LL^\mathsf{T}$.
- For $i = 1, \ldots, n$ do
  - $y_i \gets b_i - \displaystyle\sum_{j=1}^i \ell_{ij} y_j$
- $x_n \gets \dfrac{y_i}{\ell_{nn}}$
- For $i = n - 1, \ldots, 1$ do
  - $x_i \gets \dfrac{1}{\ell_{ii}} \left( y_i - \displaystyle \sum_{j=i+1}^{n} \ell_{ji} x_j \right)$
- Return $\mathbf{x} = (x_1, x_2, \ldots, x_n)$.
```

```{prf:example}
:label: cholesky-solution-example

Solve the following system of linear equations using the Cholesky-Crout method.

$$ \begin{align*}
    \begin{pmatrix}
        4 & -2 & -4\\
        -2 & 10 & 5\\
        -4 & 5 & 14
    \end{pmatrix}
    \begin{pmatrix}
        x_1 \\ x_2 \\ x_3 \end{pmatrix} =
    \begin{pmatrix} -2 \\ 49 \\ 27 \end{pmatrix}.
\end{align*} $$

---

**Solution**

We saw in {prf:ref}`cholesky-example` that the Cholesky decomposition of the matrix $A$ is 

$$ L=\begin{pmatrix} 2 & 0 & 0 \\ -1 & 3 & 0 \\ -2 & 1 & 3 \end{pmatrix}. $$

Solving $L\mathbf{y}=\mathbf{b}$ using forward substitution

$$ \begin{align*}
    \begin{pmatrix}
        2 & 0 & 0\\
        -1 & 3 & 0\\
        -2 & 1 & 3
    \end{pmatrix}
    \begin{pmatrix} y_1 \\ y_2 \\ y_3 \end{pmatrix} =
    \begin{pmatrix} -2 \\ 49 \\ 27 \end{pmatrix},
\end{align*} $$

gives

$$ \begin{align*}
    y_1 &=\frac{-2}{2}=-1,\\
    y_2 &=\frac{1}{3}(49+y_1 )=\frac{1}{3}(49-1)=16,\\
    y_3 &=\frac{1}{3}(27+2y_1 -y_2 )=\frac{1}{3}(27+2(-1)-16)=3.
\end{align*} $$

Solving $L^\mathsf{T} \mathbf{x}=\mathbf{y}$ using back substitution

$$ \begin{align*}
    \begin{pmatrix}
        2 & -1 & -2\\
        0 & 3 & 1\\
        0 & 0 & 3
    \end{pmatrix}
    \begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix} =
    \begin{pmatrix} -1 \\ 16 \\ 3 \end{pmatrix},
\end{align*} $$

gives

$$ \begin{align*}
    x_3 &=\frac{3}{3}=1,\\
    x_2 &=\frac{1}{3}(16-x_3 )=\frac{1}{3}(16-1)=5,\\
    x_1 &=\frac{1}{2}(-1+x_2 +2x_3 )=\frac{1}{2}(-1+5+2(1))=3.
\end{align*} $$

So the solution is $\mathbf{x}=(3,5,1)$.
```

In [2]:
import numpy as np

def forward_substitution(L, b):
    n = L.shape[0]
    x = np.zeros(n)
    for i in range(n):
        sum_ = 0
        for j in range(i):
            sum_ += L[i,j] * x[j]
            
        x[i] = (b[i] - sum_) / L[i,i]
    
    return x


def back_substitution(U, b):
    n = U.shape[0]
    x = np.zeros(n)
    x[-1] = b[-1] / U[-1,-1]
    for i in range(n - 2, -1, -1):
        sum_ = 0
        for j in range(i + 1, n):
            sum_ += U[i,j] * x[j]
            
        x[i] = (b[i] - sum_) / U[i,i]
        
    return x


# Define system
A = np.array([[4, -2, -4], 
              [-2, 10, 5], 
              [-4, 5, 14]])
b = np.array([-2, 49, 27])

# Calculate Cholesky decomposition
L = cholesky(A)
print(f"L = \n{L}\n")

# Solve system
y = forward_substitution(L, b)
x = back_substitution(L.T, y)
print(f"x = {x}")

L = 
[[ 2.  0.  0.]
 [-1.  3.  0.]
 [-2.  1.  3.]]

x = [3. 5. 1.]
