(eigenvalues-using-qr-decomposition-section)=

# Calculating eigenvalues using QR decomposition

<a href="https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors" target="_blank">Eigenvalues and eigenvectors</a> feature prominently in the study of numerical methods for ODEs. Given a system of ODEs, the eigenvalues of the coefficient matrix provide information about the stability, divergence, oscillatory behavior, and constant solutions of the system. 

```{prf:definition} Eigenvalue
:label: eigenvalue-definition

Let $A$ be an $n \times n$ matrix. A scalar $\lambda$ is an **eigenvalue** of $A$ if there exists a non-zero vector $\mathbf{v}$ such that 

$$A \mathbf{v} = \lambda \mathbf{v}.$$(eigenvalue-definition-equation)

The vector $\mathbf{v}$ is called the **eigenvector** associated with the eigenvalue $\lambda$.
```

Rearranging equation {eq}`eigenvalue-definition-equation` we have

$$ \begin{align*}
    A \mathbf{v} &= \lambda \mathbf{v} \\
    (A - \lambda I) \mathbf{v} &= \mathbf{0}.
\end{align*} $$

Since $\mathbf{v} \ne \mathbf{0}$, the homogeneous system $(A - \lambda I) \mathbf{v} = \mathbf{0}$ has non-trivial solution. This occurs if and only if $A - \lambda I$ is singular, which means

$$ \det(A - \lambda I) = 0.$$(eigenvalue-determinant-formula-equation)

For example, consider the eigenvalues of the matrix

$$ A = \begin{pmatrix} 2 & 1 \\ 2 & 3 \end{pmatrix}.$$

Using equation {eq}`eigenvalue-determinant-formula-equation`

$$ \begin{align*}
    \det \begin{pmatrix} 2 - \lambda & 1 \\ 2 & 3 - \lambda \end{pmatrix} &= 0 \\
    \lambda^2 - 5 \lambda + 4 &= 0 \\
    (\lambda - 1)(\lambda - 4) &= 0
\end{align*} $$

so the eigenvalues are $\lambda_1 = 4$ and $\lambda_2 = 1$ [^1]. The problem with using determinants to calculate eigenvalues is that it is too computationally expensive for larger matrices.

[^1]: Eigenvalues are usually listed in descending order by their absolute values.

---

## The QR algorithm

Although the characteristic polynomial can be used to determine eigenvalues analytically for small matrices, it becomes computationally expensive and numerically unreliable for large matrices. Modern numerical software therefore uses iterative methods such as the QR algorithm.

The **QR algorithm** is a method of computing the eigenvalues of a square matrix $A$. Let 

$$ A_0 = A, $$ 

and for $k = 0, 1, \ldots, $

$$ \begin{align*}
    A_k &= Q_k R_k,\\
    A_{k+1} &= R_k Q_k.
\end{align*} $$

Since $Q_k$ is orthogonal then $Q^{-1} = Q^T$ and

$$ A_{k+1} = R_kQ_k = Q_k^{-1} (Q_kR_k) Q_k = Q^{-1}A_kQ_k = Q_k^\mathrm{T}A_kQ_k. $$

Since 

$$ A_{k+1} = Q_k^\mathsf{T} A_k Q_k, $$

each iterate is similar to the previous iterate. Therefore all matrices $A_0, A_1, A_2, \ldots $ have exactly the same eigenvalues. Under suitable conidtions, $A_k$ converges to an upper triangular matrix.

$$ A_{k} =
\begin{pmatrix}
    \lambda_1 & \star & \cdots & \star \\
    0 & \lambda_2 & \ddots & \vdots \\
    \vdots & \ddots & \ddots & \star \\
    0 & \cdots & 0 & \lambda_n 
\end{pmatrix}. $$

```{prf:theorem} QR algorithm

Let $A_0 = A$ and suppose

$$ A_k = Q_kR_k, $$

is the QR decomposition of $A_k$. Define

$$ A_{k+1} = R_kQ_k. $$

Then

$$ A_{k+1} = Q_k^\mathsf{T} A_k Q_k, $$

so $A_{k+1}$ is similar to $A_k$ and therefore has the same eigenvalues.
```

```{prf:algorithm} The QR algorithm
:label: qr-algorithm

**Inputs:** An $n \times n$ matrix $A$ and an accuracy tolerance $tol$.

**Outputs:** A vector $(\lambda_1, \lambda_2, \ldots, \lambda_n)$ containing the eigenvalues of $A$.

- for $k = 1, 2, \ldots$
  - Calculate the QR decomposition of $A$
  - $A \gets R Q$
  - If $\max(|a_{ij}| \text{ for } i > j) < tol$
    - Break
- Return $\operatorname{diag}(A)$
```

```{prf:example}
:label: qr-algorithm-example

Use the QR algorithm to compute the eigenvalues of the matrix

$$ A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}, $$

using an accuracy tolerance of $tol = 10^{-4}$. 

---

**Solution**

Calculate the QR decomposition of $A_0$

$$ \begin{align*}
    Q_0 &= \begin{pmatrix} 
         0.3162 & 0.9487 \\ 
         0.9487 & -0.3162 
    \end{pmatrix}, \\
    R_0 &= \begin{pmatrix} 
        3.1623 & 4.4272 \\
        0 & 0.6325
    \end{pmatrix}
\end{align*} $$

and calculate $A_1 = R_0Q_0$

$$ \begin{align*}
    A_1 &= 
    \begin{pmatrix} 
        3.1623 & 4.4272 \\
        0 & 0.6325
    \end{pmatrix}
    \begin{pmatrix} 
        0.3162 & 0.9487 \\ 
        0.9487 & -0.3162 
    \end{pmatrix} \\
    &=
    \begin{pmatrix}
        5.2 & 1.6 \\
        0.6 & -0.2 
    \end{pmatrix}
\end{align*} $$

Calculate the QR decomposition of $A_1$

$$ \begin{align*}
    Q_1 &=
    \begin{pmatrix}
        0.9943 & 0.1146 \\
        0.1146 & -0.9934
    \end{pmatrix}, \\
    R_1 &= 
    \begin{pmatrix}
        5.2345 & 1.5665 \\
        0 & 0.3821
    \end{pmatrix}
\end{align*} $$

and calculate $A_2 = R_1Q_1$

$$ \begin{align*}
    A_2 &=
    \begin{pmatrix}
        5.2345 & 1.5665 \\
        0 & 0.3821
    \end{pmatrix}
    \begin{pmatrix}
        0.9943 & 0.1146 \\
        0.1146 & -0.9934
    \end{pmatrix} \\
    &=
    \begin{pmatrix}
        5.3796 & -0.9562 \\
        0.0438 & -0.3796
    \end{pmatrix} .
\end{align*} $$

Calculate the maximum difference between the diagonal elements of $A_1$ and $A_2$

$$ \begin{align*}
    \max(|\operatorname{diag}(A_2 - A_1)|) 
    &= \max \left ( \left|
        \begin{pmatrix} 5.3796 \\ -0.3796 \end{pmatrix} -
        \begin{pmatrix} 5.2 \\ -0.2 \end{pmatrix}
    \right| \right) \\
    &= \max \begin{pmatrix}  0.1796 \\ 0.1796 \end{pmatrix} = 0.1796,
\end{align*} $$

since $0.1796 > 10^{-4}$ we need to continue to iterate. The estimates of the eigenvalues obtained by iterating to an accuracy tolerance of $10^{-4}$ are tabulated below. 

| $k$ | $\lambda_1$ | $\lambda_2$ | Max difference |
|:--:|:--------:|:---------:|:--------:|
|  0 | 5.200000 | -0.200000 | 4.20e+00 |
|  1 | 5.379562 | -0.379562 | 1.80e-01 |
|  2 | 5.371753 | -0.371753 | 7.81e-03 |
|  3 | 5.372318 | -0.372318 | 5.65e-04 |
|  4 | 5.372279 | -0.372279 | 3.90e-05 |

The exact values of the eigenvalues are $\lambda_1 = (5 + \sqrt{33})/2 \approx 5.372281$ and $\lambda_2 = (5 - \sqrt{33}) / 2 \approx -0.372281$ which shows the QR algorithm has calculated the eigenvalues correct to five decimal places.
```

In [1]:
import numpy as np

def qr_householder(A):
    
    m, n = A.shape
    Q, R = np.eye(m), np.copy(A)

    for i in range(m - 1):
        x = R[i:,i]
        v = np.array([x - np.linalg.norm(x) * np.eye(m - i)[:,0]]).T
        H = np.eye(m)
        H[i:,i:] -= 2 * np.dot(v, v.T) / np.dot(v.T, v)
        R = np.dot(H, R)
        Q = np.dot(Q, H)

    for i in range(n):
        if R[i,i] < 0:
            R[i,:] = -R[i,:]
            Q[:,i] = -Q[:,i]

    return Q, R


A = np.array([[1, 2], [3, 4]])

Q, R = qr_householder(A)
print("Q =\n", Q)
print("R =\n", R)

A1 = np.dot(R, Q)
print("A1 =\n", A1)

Q, R = qr_householder(A1)
print("Q =\n", Q)
print("R =\n", R)

A2 = np.dot(R, Q)
print("A2 =\n", A2)

print(f"diff = {max(abs(np.diag(A2 - A1))):0.4f}")

Q =
 [[ 0.31622777  0.9486833 ]
 [ 0.9486833  -0.31622777]]
R =
 [[3.16227766e+00 4.42718872e+00]
 [4.44089210e-16 6.32455532e-01]]
A1 =
 [[ 5.2  1.6]
 [ 0.6 -0.2]]
Q =
 [[ 0.99340894  0.11462411]
 [ 0.11462411 -0.99340894]]
R =
 [[5.23450093e+00 1.56652948e+00]
 [3.15106627e-16 3.82080360e-01]]
A2 =
 [[ 5.37956204 -0.95620438]
 [ 0.04379562 -0.37956204]]
diff = 0.1796


In [15]:
def eigvals(A, tol=1e-6):
    for _ in range(20):
        Q, R = qr_householder(A)
        A = R @ Q
        if np.max(abs(np.tril(A, -1))) < tol:
            break

    return np.diagonal(A)


# # Define matrix
A = np.array([[1, 2],
              [3, 4]])

# Calculate eigenvalues
lambda_ = eigvals(A, 1e-4)
print(lambda_)

[ 5.37227879 -0.37227879]


In [9]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(max(abs(np.tril(A, -1))))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()