# Exam 2023/24 Solutions

---

#### Question 4

(a)  See handwritten solutions.

(b) 

In [1]:
import sympy as sp

a21, a31, a32, a41, a42, a43, b1, b2, b3, b4 = sp.symbols('a21, a31, a32, a41, a42, a43, b1, b2, b3, b4')
c2, c3, c4 = sp.Rational(1, 3), sp.Rational(2, 3), 1

eq1 = b1 + b2 + b3 + b4 - 1
eq2 = b2 * c2 + b3 * c3 + b4 * c4 - sp.Rational(1, 2)
eq3 = b2 * c2 ** 2 + b3 * c3 ** 2 + b4 * c4 ** 2 - sp.Rational(1, 3)
eq4 = b2 * c2 ** 3 + b3 * c3 ** 3 + b4 * c4 ** 3 - sp.Rational(1, 4)
eq5 = b3 * a32 * c2 + b4 * a42 * c2 + b4 * a43 * c3 - sp.Rational(1, 6)
eq6 = b3 * a32 * c2 * c3 + b4 * a42 * c2 * c4 + b4 * a43 * c3 * c4 - sp.Rational(1, 8)
eq7 = b3 * a32 * c2 ** 2 + b4 * a42 * c2 ** 2 + b4 * a43 * c3 ** 2 - sp.Rational(1, 12)
eq8 = b4 * a43 * a32 * c2 - sp.Rational(1, 24)
eq9 = c2 - a21
eq10 = c3 - a31 - a32
eq11 = c4 - a41 - a42 - a43

sp.solve((eq1, eq2, eq3, eq4, eq5, eq6, eq7, eq8, eq9, eq10, eq11))

{a31: -1/3,
 a32: 1,
 a41: 1,
 a42: -1,
 a43: 1,
 b1: 1/8,
 b2: 3/8,
 b3: 3/8,
 b4: 1/8,
 a21: 1/3}

\begin{align*}
  \begin{array}{c|cccc}
    0 & 0 \\
    \frac{1}{3} & \frac{1}{3} \\
    \frac{2}{3} & -\frac{1}{3} & 1 \\
    1 & 1 & -1 & 1 \\ \hline
    & \frac{1}{8} & \frac{3}{8} & \frac{3}{8} & \frac{1}{8}
  \end{array}
\end{align*}

(c)

In [11]:
import numpy as np

def f(t, y):
    return -3 * t * y

h =  0.1
t = 0
y = 1

nsteps = int(1/2 / h)

print("  t   |    y \n-----------------")

for n in range(nsteps):
    k1 = f(t, y)
    k2 = f(t + 1/3 * h, y + 1/3 * h * k1)
    k3 = f(t + 2/3 * h, y + h * (-1/3 * k1 + k2))
    k4 = f(t + h, y + h * (k1 - k2 + k3))
    y = y + h / 8 * (k1 + 3 * k2 + 3 * k3 + k4)
    t = t + h

    print(f" {t:0.2f} | {y:0.6f} ")

  t   |    y 
-----------------
 0.10 | 0.985112 
 0.20 | 0.941764 
 0.30 | 0.873714 
 0.40 | 0.786625 
 0.50 | 0.687286 


---
#### Question 5


In [21]:
x = sp.symbols('x')
c = sp.solve(20 * x ** 3 - 30 * x ** 2 + 12 * x -1)
print(c)

[1/2, 1/2 - sqrt(15)/10, sqrt(15)/10 + 1/2]


In [25]:
c1 = sol[1]
c2 = sol[0]
c3 = sol[2]

eq1 = b1 + b2 + b3 - 1
eq2 = b1 * c1 + b2 * c2 + b3 * c3 - sp.Rational(1,2)
eq3 = b1 * c1 ** 2 + b2 * c2 ** 2 + b3 * c3 ** 2 - sp.Rational(1,3)

sp.solve((eq1, eq2, eq3))

{b1: 5/18, b2: 4/9, b3: 5/18}

In [28]:
a11, a12, a13, a22, a23, a33 = sp.symbols('a11, a12, a13, a22, a23, a33')

eq1 = a11 + a12 + a13 - c1
eq2 = a21 + a22 + a23 - c2
eq3 = a31 + a32 + a33 - c3
eq4 = a11 * c1 + a12 * c2 + a13 * c3 - sp.Rational(1,2) * c1 ** 2
eq5 = a21 * c1 + a22 * c2 + a23 * c3 - sp.Rational(1,2) * c2 ** 2
eq6 = a31 * c1 + a32 * c2 + a33 * c3 - sp.Rational(1,2) * c3 ** 2
eq7 = a11 * c1 ** 2 + a12 * c2 ** 2 + a13 * c3 ** 2 - sp.Rational(1,3) * c1 ** 3
eq8 = a21 * c1 ** 2 + a22 * c2 ** 2 + a23 * c3 ** 2 - sp.Rational(1,3) * c2 ** 3
eq9 = a31 * c1 ** 2 + a32 * c2 ** 2 + a33 * c3 ** 2 - sp.Rational(1,3) * c3 ** 3

sp.solve((eq1, eq2, eq3, eq4, eq5, eq6, eq7, eq8, eq9))


{a11: 5/36,
 a12: 2/9 - sqrt(15)/15,
 a13: 5/36 - sqrt(15)/30,
 a21: 5/36 + sqrt(15)/24,
 a22: 2/9,
 a23: 5/36 - sqrt(15)/24,
 a31: sqrt(15)/30 + 5/36,
 a32: 2/9 + sqrt(15)/15,
 a33: 5/36}

---

#### Question 6

(a) See handwritten solutions

(b)

In [52]:
A = np.array([[1, 3, 2], [2, 5, 1], [3, 7, 2]])

L = np.tril(A, -1)
U = np.triu(A, 1)
D = A - L - U

TJ = -np.dot(np.linalg.inv(D), L + U)
TGS = -np.dot(np.linalg.inv(L + D), U)

print("TJ = \n", TJ)
print("TGS = \n", TGS)

rhoTJ = max(abs(np.linalg.eig(TJ)[0]))
rhoTGS = max(abs(np.linalg.eig(TGS)[0]))

print(f"\nrho(TJ) = {rhoTJ:0.4f}")
print(f"rho(TGS) = {rhoTGS:0.4f}")

TJ = 
 [[-0.  -3.  -2. ]
 [-0.4 -0.  -0.2]
 [-1.5 -3.5 -0. ]]
TGS = 
 [[-0.  -3.  -2. ]
 [-0.   1.2  0.6]
 [-0.   0.3  0.9]]

rho(TJ) = 2.5232
rho(TGS) = 1.5000


(c)

In [60]:
x = [0, 0, 0]

print("   k | x1 | x2 | x3 \n--------------------------------")
print(f" {0:3d} | {x[0]:0.6f} | {x[1]:0.6f} | {x[2]:0.6f}")

for k in range(5):
    x[0] = 0.2 - 3 * x[1] - 2 * x[2]
    x[1] = 4.7 - 2 * x[0] + x[2]
    x[2] = 5.8 - 3 * x[0] - 7 * x[1]

    print(f" {k+1:3d} | {x[0]:0.6f} | {x[1]:0.6f} | {x[2]:0.6f}")

   k | x1 | x2 | x3 
--------------------------------
   0 | 0.000000 | 0.000000 | 0.000000
   1 | 0.200000 | 4.300000 | -24.900000
   2 | 37.100000 | -94.400000 | 555.300000
   3 | -827.200000 | 2214.400000 | -13013.400000
   4 | 19383.800000 | -51776.300000 | 304288.500000
   5 | -453247.900000 | 1210789.000000 | -7115773.500000
