# Chapter 6 Exercise Solutions

---

#### Exercise 6.1

In [849]:
import sympy as sp

A = sp.Matrix([[2, 3, -1], [4, 9, -1], [0, 3, 2]])
b = sp.Matrix([4, 18, 11])

L, U = sp.eye(3), sp.zeros(3)

# j = 1
U[0,0] = A[0,0]
L[1,0] = A[1,0] / U[0,0]
L[2,0] = A[2,0] / U[0,0]

# j = 2
U[0,1] = A[0,1]
U[1,1] = A[1,1] - L[1,0] * U[0,1]
L[2,1] = (A[2,1] - L[2,0] * U[0,1]) / U[1,1]

# j = 3
U[0,2] = A[0,2]
U[1,2] = A[1,2] - L[1,0] * U[0,2]
U[2,2] = A[2,2] - L[2,0] * U[0,2] - L[2,1] * U[1,2]

print(f"L =")
sp.pprint(L)
print(f"\nU =")
sp.pprint(U)

L =
⎡1  0  0⎤
⎢       ⎥
⎢2  1  0⎥
⎢       ⎥
⎣0  1  1⎦

U =
⎡2  3  -1⎤
⎢        ⎥
⎢0  3  1 ⎥
⎢        ⎥
⎣0  0  1 ⎦


Solve $L\mathbf{y} = \mathbf{b}$.

In [850]:
y = sp.zeros(3, 1)
y[0] = b[0]
y[1] = b[1] - L[1,0] * y[0]
y[2] = b[2] - L[2,0] * y[0] - L[2,1] * y[1]

print(f"\ny =")
sp.pprint(y)


y =
⎡4 ⎤
⎢  ⎥
⎢10⎥
⎢  ⎥
⎣1 ⎦


Solve $U \mathbf{x} = \mathbf{y}$.

In [851]:
# Solve Ux = y
x = sp.zeros(3, 1)
x[2] = y[2] / U[2,2]
x[1] = (y[1] - U[1,2] * x[2]) / U[1,1]
x[0] = (y[0] - U[0,1] * x[1] - U[0,2] * x[2]) / U[0,0]

print(f"\nx =")
sp.pprint(x)


x =
⎡-2⎤
⎢  ⎥
⎢3 ⎥
⎢  ⎥
⎣1 ⎦


---

#### Exercise 6.2

Apply partial pivotring to calculate the permutation matrix $P$.

In [852]:
A = sp.Matrix([[1, 3, 2], [2, 1, 0], [3, 1, -1]])
b = sp.Matrix([16, 0, -5])

sp.pprint(A)

⎡1  3  2 ⎤
⎢        ⎥
⎢2  1  0 ⎥
⎢        ⎥
⎣3  1  -1⎦


In [853]:
A = A.elementary_row_op('n<->m', 0, 2)
sp.pprint(A)

⎡3  1  -1⎤
⎢        ⎥
⎢2  1  0 ⎥
⎢        ⎥
⎣1  3  2 ⎦


In [854]:
A = A.elementary_row_op('n<->m', 1, 2)
sp.pprint(A)

⎡3  1  -1⎤
⎢        ⎥
⎢1  3  2 ⎥
⎢        ⎥
⎣2  1  0 ⎦


In [855]:
P = sp.eye(3)
P = P.elementary_row_op('n<->m', 0, 2).elementary_row_op('n<->m', 1, 2)
sp.pprint(P)

⎡0  0  1⎤
⎢       ⎥
⎢1  0  0⎥
⎢       ⎥
⎣0  1  0⎦


Calculate LUP decomposition of $PA$.

In [856]:
L, U = sp.eye(3), sp.zeros(3)

# j = 1
U[0,0] = A[0,0]
L[1,0] = A[1,0] / U[0,0]
L[2,0] = A[2,0] / U[0,0]

# j = 2
U[0,1] = A[0,1]
U[1,1] = A[1,1] - L[1,0] * U[0,1]
L[2,1] = (A[2,1] - L[2,0] * U[0,1]) / U[1,1]

# j = 3
U[0,2] = A[0,2]
U[1,2] = A[1,2] - L[1,0] * U[0,2]
U[2,2] = A[2,2] - L[2,0] * U[0,2] - L[2,1] * U[1,2]

print(f"L =")
sp.pprint(L)
print(f"\nU =")
sp.pprint(U)

L =
⎡ 1    0   0⎤
⎢           ⎥
⎢1/3   1   0⎥
⎢           ⎥
⎣2/3  1/8  1⎦

U =
⎡3   1   -1 ⎤
⎢           ⎥
⎢0  8/3  7/3⎥
⎢           ⎥
⎣0   0   3/8⎦


Solve $L \mathbf{y} = P\mathbf{b}$.

In [857]:
y = sp.zeros(3, 1)
b = P * b
y[0] = b[0]
y[1] = b[1] - L[1,0] * y[0]
y[2] = b[2] - L[2,0] * y[0] - L[2,1] * y[1]

print(f"\ny =")
sp.pprint(y)


y =
⎡ -5 ⎤
⎢    ⎥
⎢53/3⎥
⎢    ⎥
⎣9/8 ⎦


Solve $U \mathbf{x} = \mathbf{y}$.  

In [858]:
x = sp.zeros(3, 1)
x[2] = y[2] / U[2,2]
x[1] = (y[1] - U[1,2] * x[2]) / U[1,1]
x[0] = (y[0] - U[0,1] * x[1] - U[0,2] * x[2]) / U[0,0]

print(f"\nx =")
sp.pprint(x)


x =
⎡-2⎤
⎢  ⎥
⎢4 ⎥
⎢  ⎥
⎣3 ⎦


---

#### Exercise 6.3

In [859]:
A = sp.Matrix([[16, 16, 4], [16, 25, 10], [4, 10, 6]])
b = sp.Matrix([-8, -47, -30])

sp.pprint(A)

⎡16  16  4 ⎤
⎢          ⎥
⎢16  25  10⎥
⎢          ⎥
⎣4   10  6 ⎦


Check whether $A$ is positive definite.

In [860]:
sp.pprint(A.T)

⎡16  16  4 ⎤
⎢          ⎥
⎢16  25  10⎥
⎢          ⎥
⎣4   10  6 ⎦


In [861]:
print(A[:1,:1].det())
print(A[:2,:2].det())
print(A.det())

16
144
144


Calculate Cholesky decomposition of $A$.

In [862]:
L = sp.zeros(3, 3)
L[0,0] = sp.sqrt(A[0,0])
L[1,0] = A[1,0] / L[0,0]
L[2,0] = A[2,0] / L[0,0]
L[1,1] = sp.sqrt(A[1,1] - L[1,0]**2)
L[2,1] = (A[2,1] - L[2,0] * L[1,0]) / L[1,1]
L[2,2] = sp.sqrt(A[2,2] - L[2,0]**2 - L[2,1]**2)

print("L =")
sp.pprint(L)

L =
⎡4  0  0⎤
⎢       ⎥
⎢4  3  0⎥
⎢       ⎥
⎣1  2  1⎦


Solve $L\mathbf{y} = \mathbf{b}$.

In [863]:
y = sp.zeros(3, 1)
y[0] = b[0] / L[0,0]
y[1] = (b[1] - L[1,0] * y[0]) / L[1,1]
y[2] = (b[2] - L[2,0] * y[0] - L[2,1] * y[1]) / L[2,2]

print("y =")
sp.pprint(y)

y =
⎡-2 ⎤
⎢   ⎥
⎢-13⎥
⎢   ⎥
⎣-2 ⎦


Solve $L^\mathsf{T} \mathbf{x} = \mathbf{y}$.

In [864]:
x = sp.zeros(3, 1)
L = L.T
x[2] = y[2] / L[2,2]
x[1] = (y[1] - L[1,2] * x[2]) / L[1,1]
x[0] = (y[0] - L[0,1] * x[1] - L[0,2] * x[2]) / L[0,0]

print("x =")
sp.pprint(x)

x =
⎡3 ⎤
⎢  ⎥
⎢-3⎥
⎢  ⎥
⎣-2⎦


---

#### Exercise 6.4

Exercise 6.1 solution

In [865]:
import numpy as np

def lu(A):
    n = A.shape[0]
    L, U = np.eye(n), np.zeros((n, n))
    
    for j in range(n):
        for i in range(j+1):
            sum_ = 0
            for k in range(i):
                sum_ += L[i,k] * U[k,j]
            
            U[i,j] = A[i,j] - sum_
        
        for i in range(j+1, n):
            sum_ = 0
            for k in range(i):
                sum_ += L[i,k] * U[k,j]

            L[i,j] = (A[i,j] - sum_) / U[j,j]
                
    return L, U


def forward_substitution(L, b):
    n = L.shape[0]
    x = np.zeros(n)
    for i in range(n):
        sum_ = 0
        for j in range(i):
            sum_ += L[i,j] * x[j]
            
        x[i] = (b[i] - sum_) / L[i,i]
    
    return x


def back_substitution(U, b):
    n = U.shape[0]
    x = np.zeros(n)
    x[-1] = b[-1] / U[-1,-1]
    for i in range(n - 2, -1, -1):
        sum_ = 0
        for j in range(i + 1, n):
            sum_ += U[i,j] * x[j]
            
        x[i] = (b[i] - sum_) / U[i,i]
        
    return x


A = np.array([[ 2, 3, -1] , [4, 9, -1 ], [ 0, 3, 2 ]])
b = np.array([ 4, 18, 11 ])

L, U = lu(A)
y = forward_substitution(L, b)
x = back_substitution(U, y)

print(f'L = \n{L}')
print(f'\nU = \n{U}')
print(f'\ny = {y}')
print(f'\nx = {x}')

L = 
[[1. 0. 0.]
 [2. 1. 0.]
 [0. 1. 1.]]

U = 
[[ 2.  3. -1.]
 [ 0.  3.  1.]
 [ 0.  0.  1.]]

y = [ 4. 10.  1.]

x = [-2.  3.  1.]


Exercise 6.2 solution

In [866]:
def partial_pivot(A):
    n = A.shape[0]
    P = np.eye(n)
    for j in range(n):
        maxpivot, maxpivotrow = abs(A[j,j]), j
        for i in range(j + 1, n):
            if abs(A[i,j]) > maxpivot:
                maxpivot, maxpivotrow = abs(A[i,j]), i

        A[[j,maxpivotrow]] = A[[maxpivotrow,j]] 
        P[[j,maxpivotrow]] = P[[maxpivotrow,j]]

    return P


A = np.array([[ 1, 3, 2 ], [ 2, 1, 0 ], [3, 1, -1 ]])
b = np.array([ 16, 0, -5 ])

P = partial_pivot(A)
L, U = lu(A)
y = forward_substitution(L, np.dot(P, b))
x = back_substitution(U, y)

print(f'L = \n{L}')
print(f'\nU = \n{U}')
print(f'\ny = {y}')
print(f'\nx = {x}')

L = 
[[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.66666667 0.125      1.        ]]

U = 
[[ 3.          1.         -1.        ]
 [ 0.          2.66666667  2.33333333]
 [ 0.          0.          0.375     ]]

y = [-5.         17.66666667  1.125     ]

x = [-2.  4.  3.]


Exercise 6.3 solution

In [867]:
def cholesky(A):
    n = A.shape[0]
    L = np.zeros((n, n))   
    for j in range(n):
        sum_ = 0
        for k in range(j):
            sum_ += L[j,k] ** 2
        
        L[j,j] = np.sqrt(A[j,j] - sum_)
                
        for i in range(j+1, n):
            sum_ = 0
            for k in range(j):
                sum_ += L[i,k] * L[j,k]
            
            L[i,j] = (A[i,j] - sum_) / L[j,j]
    
    return L


A = np.array([[ 16, 16, 4 ], [ 16, 25, 10 ], [ 4, 10, 6 ]])
b = np.array([ -8, -47, -30 ])

L = cholesky(A)
y = forward_substitution(L, b)
x = back_substitution(L.T, y)

print(f'L = \n{L}')
print(f'\ny = {y}')
print(f'\nx = {x}')

L = 
[[4. 0. 0.]
 [4. 3. 0.]
 [1. 2. 1.]]

y = [ -2. -13.  -2.]

x = [ 3. -3. -2.]


---

#### Exercise 6.5

(a)

In [868]:
A = sp.Matrix([[1, 1], [-1, 0]])

Q, R = sp.zeros(2, 2), sp.zeros(2, 2)

# j = 1
u1 = A[:,0]
R[0,0] = u1.norm()
Q[:,0] = u1 / R[0,0]

# j = 2
u2 = A[:,1] - (Q[:,0].dot(A[:,1])) * Q[:,0]
R[0,1] = Q[:,0].dot(A[:,1])
R[1,1] = u2.norm()
Q[:,1] = u2 / R[1,1]

print("Q =")
sp.pprint(Q)
print("\nR =")
sp.pprint(R)

Q =
⎡ √2   √2⎤
⎢ ──   ──⎥
⎢ 2    2 ⎥
⎢        ⎥
⎢-√2   √2⎥
⎢────  ──⎥
⎣ 2    2 ⎦

R =
⎡    √2⎤
⎢√2  ──⎥
⎢    2 ⎥
⎢      ⎥
⎢    √2⎥
⎢0   ──⎥
⎣    2 ⎦


(b)

In [869]:
A = sp.Matrix([[6, 6, 1], [3, 6, 1], [2, 1, 1]])

Q, R = sp.zeros(3, 3), sp.zeros(3, 3)

# j = 1
u1 = A[:,0]
R[0,0] = u1.norm()
Q[:,0] = u1 / R[0,0]  

# j = 2
u2 = A[:,1] - (Q[:,0].dot(A[:,1])) * Q[:,0]
R[0,1] = Q[:,0].dot(A[:,1])
R[1,1] = u2.norm()
Q[:,1] = u2 / R[1,1]

# j = 3
u3 = A[:,2] - (Q[:,0].dot(A[:,2])) * Q[:,0] - (Q[:,1].dot(A[:,2])) * Q[:,1]
R[0,2] = Q[:,0].dot(A[:,2])
R[1,2] = Q[:,1].dot(A[:,2])
R[2,2] = u3.norm()
Q[:,2] = u3 / R[2,2]

print("Q =")
sp.pprint(Q)
print("\nR =")
sp.pprint(R)

Q =
⎡6/7  -2/7  -3/7⎤
⎢               ⎥
⎢3/7  6/7   2/7 ⎥
⎢               ⎥
⎣2/7  -3/7  6/7 ⎦

R =
⎡7  8  11/7⎤
⎢          ⎥
⎢0  3  1/7 ⎥
⎢          ⎥
⎣0  0  5/7 ⎦


(c)

In [870]:
A = sp.Matrix([[1, 2, 1], [1, 4, 3], [1, -4, 6], [1, 2, 1]])

Q, R = sp.zeros(4, 3), sp.zeros(3, 3)

# j = 1
u1 = A[:,0]
R[0,0] = u1.norm()
Q[:,0] = u1 / R[0,0]  

# j = 2
u2 = A[:,1] - (Q[:,0].dot(A[:,1])) * Q[:,0]
R[0,1] = Q[:,0].dot(A[:,1])
R[1,1] = u2.norm()
Q[:,1] = u2 / R[1,1]

# j = 3
u3 = A[:,2] - (Q[:,0].dot(A[:,2])) * Q[:,0] - (Q[:,1].dot(A[:,2])) * Q[:,1]
R[0,2] = Q[:,0].dot(A[:,2])
R[1,2] = Q[:,1].dot(A[:,2])
R[2,2] = u3.norm()
Q[:,2] = u3 / R[2,2]

print("Q =")
sp.pprint(Q)
print("\nR =")
sp.pprint(R)

Q =
⎡           -√2 ⎤
⎢1/2  1/6   ────⎥
⎢            3  ⎥
⎢               ⎥
⎢            √2 ⎥
⎢1/2  1/2    ── ⎥
⎢            2  ⎥
⎢               ⎥
⎢            √2 ⎥
⎢1/2  -5/6   ── ⎥
⎢            6  ⎥
⎢               ⎥
⎢           -√2 ⎥
⎢1/2  1/6   ────⎥
⎣            3  ⎦

R =
⎡2  2  11/2 ⎤
⎢           ⎥
⎢0  6  -19/6⎥
⎢           ⎥
⎢      11⋅√2⎥
⎢0  0  ─────⎥
⎣        6  ⎦


---

#### Exercise 6.6

(a)

In [871]:
A = sp.Matrix([[3, 0], [4, 5]])

Q, R = sp.eye(2), A.copy()

# j = 1
x = R[:,0]
v = x + x.norm() * sp.Matrix([[1], [0]])
H = sp.eye(2) - 2 * (v * v.T) / (v.T * v)[0]
R = H * R
Q = Q * H

print("Q =")
sp.pprint(Q)
print("\nR =")
sp.pprint(R)

Q =
⎡-3/5  -4/5⎤
⎢          ⎥
⎣-4/5  3/5 ⎦

R =
⎡-5  -4⎤
⎢      ⎥
⎣0   3 ⎦


The first diagonal element of $R$ is negative, so multiply the first row of $R$ by $-1$ and the first column of $Q$ by $-1$.

In [872]:
R[0,:] *= -1
Q[:,0] *= -1

print("Q =")
sp.pprint(Q)
print("\nR =")
sp.pprint(R)

Q =
⎡3/5  -4/5⎤
⎢         ⎥
⎣4/5  3/5 ⎦

R =
⎡5  4⎤
⎢    ⎥
⎣0  3⎦


(b)

In [873]:
A = sp.Matrix([[1, 2, 4], [0, 0, 5], [0, 3, 6]])

Q, R = sp.eye(3), A.copy()

print("R =")
sp.pprint(R)

R =
⎡1  2  4⎤
⎢       ⎥
⎢0  0  5⎥
⎢       ⎥
⎣0  3  6⎦


First columns of $R$ is already parallel to $e_1$, so we move to the second column.

In [874]:
x = R[1:,1]
v = x + x.norm() * sp.Matrix([[1], [0]])
Hdash = sp.eye(2) - 2 * (v * v.T) / (v.T * v)[0]
H = sp.eye(3)
H[1:,1:] = Hdash
R = H * R
Q = Q * H

print("Q =")
sp.pprint(Q)
print("\nR =")
sp.pprint(R)

Q =
⎡1  0   0 ⎤
⎢         ⎥
⎢0  0   -1⎥
⎢         ⎥
⎣0  -1  0 ⎦

R =
⎡1  2   4 ⎤
⎢         ⎥
⎢0  -3  -6⎥
⎢         ⎥
⎣0  0   -5⎦


Second and third main diagonal elements of $R$ are negative, so multiply the second and third rows of $R$ by $-1$ and the second and third columns of $Q$ by $-1$.

In [875]:
R[1:,:] *= -1
Q[:,1:] *= -1

print("Q =")
sp.pprint(Q)
print("\nR =")
sp.pprint(R)

Q =
⎡1  0  0⎤
⎢       ⎥
⎢0  0  1⎥
⎢       ⎥
⎣0  1  0⎦

R =
⎡1  2  4⎤
⎢       ⎥
⎢0  3  6⎥
⎢       ⎥
⎣0  0  5⎦


---

#### Exercise 6.7

**Exercise 6.5**

(a)

In [876]:
def qr_gramschmidt(A):
  
    n = A.shape[1]
    Q, R = np.copy(A).astype(float), np.zeros((n,n))

    for j in range(n):
        for i in range(j):
            R[i,j] = np.dot(Q[:,i], A[:,j])
            Q[:,j] = Q[:,j] - R[i,j] * Q[:,i]
        
        R[j,j] = np.linalg.norm(Q[:,j])
        Q[:,j] = Q[:,j] / R[j,j]

    for i in range(n):
        if R[i,i] < 0:
            R[i,:] *= -1
            Q[:,i] *= -1

    return Q, R
    

A = np.array([[ 1, 1 ], [ -1, 0 ] ])

Q, R = qr_gramschmidt(A)

print(f'Q = \n{Q}')
print(f'\nR = \n{R}')

Q = 
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

R = 
[[1.41421356 0.70710678]
 [0.         0.70710678]]


(b)

In [877]:
A = np.array([[ 6, 6, 1 ], [ 3, 6, 1 ], [ 2, 1, 1 ]])

Q, R = qr_gramschmidt(A)

print(f'Q = \n{Q}')
print(f'\nR = \n{R}')

Q = 
[[ 0.85714286 -0.28571429 -0.42857143]
 [ 0.42857143  0.85714286  0.28571429]
 [ 0.28571429 -0.42857143  0.85714286]]

R = 
[[7.         8.         1.57142857]
 [0.         3.         0.14285714]
 [0.         0.         0.71428571]]


(c)

In [878]:
A = np.array([[ 1, 2, 1 ], [ 1, 4, 3 ], [ 1, -4, 6 ], [ 1, 2, 1 ]])

Q, R = qr_gramschmidt(A)

print(f'Q = \n{Q}')
print(f'\nR = \n{R}')

Q = 
[[ 0.5         0.16666667 -0.47140452]
 [ 0.5         0.5         0.70710678]
 [ 0.5        -0.83333333  0.23570226]
 [ 0.5         0.16666667 -0.47140452]]

R = 
[[ 2.          2.          5.5       ]
 [ 0.          6.         -3.16666667]
 [ 0.          0.          2.59272486]]


**Exercise 6.6**

(a)

In [881]:
def qr_householder(A):
    
    m, n = A.shape
    Q, R = np.eye(m), np.copy(A).astype(float)

    for i in range(m - 1):
        x = R[i:,i]
        v = np.array([x + np.sign(x[0]) *  np.linalg.norm(x) * np.eye(m - i)[:,0]]).T
        H = np.eye(m)
        H[i:,i:] -= 2 * np.dot(v, v.T) / np.dot(v.T, v)
        R = np.dot(H, R)
        Q = np.dot(Q, H)

    for i in range(n):
        if R[i,i] < 0:
            R[i,:] *= -1
            Q[:,i] *= -1

    return Q, R


A = np.array([[ 3, 0 ], [ 4, 5 ]])

Q, R = qr_householder(A)

print(f'Q = \n{Q}')
print(f'\nR = \n{R}')

Q = 
[[ 0.6 -0.8]
 [ 0.8  0.6]]

R = 
[[ 5.0000000e+00  4.0000000e+00]
 [-4.4408921e-16  3.0000000e+00]]


(b)

In [880]:
A = np.array([[ 1, 2, 4 ], [ 0, 0, 5 ], [ 0, 3, 6 ]])

Q, R = qr_householder(A)

print(f'Q = \n{Q}')
print(f'\nR = \n{R}')

Q = 
[[ 1. -0. -0.]
 [-0. -0.  1.]
 [-0.  1. -0.]]

R = 
[[ 1.  2.  4.]
 [-0.  3.  6.]
 [-0. -0.  5.]]
