(matrix-decomposition-exercises-section)=

# Matrix decomposition exercises

`````{exercise}
:label: ex-lu

Using pen and paper, solve the following system of linear equations using {prf:ref}`LU decomposition<lu-theorem>`.

$$\begin{align*}
    2 x_1 + 3 x_2 -   x_3   &=  4,\\
    4 x_1 + 9 x_2 -   x_3   &= 18,\\
            3 x_2 + 2 x_3 &= 11.
\end{align*} $$

```{dropdown} Solution
$$ \begin{align*}
  L &= \begin{pmatrix}
    1 & 0 & 0 \\
    2 & 1 & 0 \\
    0 & 1 & 1
  \end{pmatrix}, &
  U &= \begin{pmatrix}
    2 & 3 & -1 \\
    0 & 3 & 1 \\
    0 & 0 & 1
  \end{pmatrix}, &
  \mathbf{x} &= \begin{pmatrix} -2 \\ 3 \\ 1 \end{pmatrix}
\end{align*} $$
```
`````


In [ ]:
import numpy as np

def lu(A):
    n = A.shape[0]
    L, U = np.eye(n), np.zeros((n, n))
    for j in range(n):
        for i in range(n):
            sum_ = 0
            if i <= j:
                for k in range(i):
                    sum_ += L[i,k] * U[k,j]
        
                U[i,j] = A[i,j] - sum_   
            
            else:         
                for k in range(j):
                    sum_ += L[i,k] * U[k,j]
                    
                L[i,j] = (A[i,j] - sum_) / U[j,j]
    
    return L, U


A = np.array([[2, 3, -1], [4, 9, -1], [0, 3, 2]])
b = np.array([4, 18, 11])
L, U = lu(A)

print('(a)')
print(f'L = {L}')
print(f'\nU = {U}')
print(f'\ny = {np.linalg.solve(L, b)}')
print(f'\nx = {np.linalg.solve(A, b)}')

(a)
L = [[1. 0. 0.]
 [2. 1. 0.]
 [0. 1. 1.]]

U = [[ 2.  3. -1.]
 [ 0.  3.  1.]
 [ 0.  0.  1.]]

y = [ 4. 10.  1.]

x = [-2.  3.  1.]


````{exercise}
:label: ex-lup

Using pen and paper, solve the following system of linear equations using [LU decomposition with partial pivoting](lup-section).

$$ \begin{align*}
    x_1 + 3x_2 + 2x_3 &= 16, \\
    2x_1 + x_2 &= 0, \\
    3x_1 + x_2 - x_3 &= -5.
\end{align*} $$

```{dropdown} Solution
$$ \begin{align*}
L &= 
  \begin{pmatrix}
    1 & 0 & 0 \\
    \frac{1}{3} & 1 & 0 \\
    \frac{2}{3} & \frac{1}{8} & 1
  \end{pmatrix}, 
  \qquad
  U &= 
  \begin{pmatrix}
    3 & 1 & -1 \\
    0 & \frac{8}{3} & \frac{7}{3} \\
    0 & 0 & \frac{3}{8}
  \end{pmatrix}, 
  \qquad
  \mathbf{x} &= \begin{pmatrix} -2 \\ 4 \\ 3 \end{pmatrix}
\end{align*} $$
```
````


In [11]:
def partial_pivot(A):
    n = A.shape[0]
    P = np.eye(n)
    for j in range(n):
        maxpivot, maxpivotrow = abs(A[j,j]), j
        for i in range(j + 1, n):
            if abs(A[i,j]) > maxpivot:
                maxpivot, maxpivotrow = abs(A[i,j]), i

        A[[j,maxpivotrow]] = A[[maxpivotrow,j]] 
        P[[j,maxpivotrow]] = P[[maxpivotrow,j]]

    return P


A = np.array([[0, 3, 2], [4, 9, -1], [2, 3, -1]])
b = np.array([11, 18, 4])

P = partial_pivot(A)
L, U = lu(A)
y = np.linalg.solve(L, np.dot(P, b))
x = np.linalg.solve(U, y)

print(f'P = {P}')
print(f'\nPA = {A}')
print(f'\nL = {L}')
print(f'\nU = {U}')
print(f'\ny = {y}')
print(f'\nx = {x}')

P = [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

PA = [[ 4  9 -1]
 [ 0  3  2]
 [ 2  3 -1]]

L = [[ 1.   0.   0. ]
 [ 0.   1.   0. ]
 [ 0.5 -0.5  1. ]]

U = [[ 4.   9.  -1. ]
 [ 0.   3.   2. ]
 [ 0.   0.   0.5]]

y = [18.  11.   0.5]

x = [-2.  3.  1.]



````{exercise}
:label: ex-cholesky

Using pen and paper, solve the following systems of linear equations using [Cholesky decomposition](cholesky-section).

$$ \begin{align*}
    16x_1 +16x_2 +4x_3 &=-8,\\
    16x_1 +25x_2 +10x_3 &=-47,\\
    4x_1 +10x_2 +6x_3 &=-30.
\end{align*} $$

```{dropdown} Solution
$$ \begin{align*}
  L = 
  \begin{pmatrix}
    4 & 0 & 0 \\
    4 & 3 & 0 \\
    1 & 2 & 1 
  \end{pmatrix}, 
  \qquad
  \mathbf{x} = \begin{pmatrix} 3 \\ 3 \\ -2 \end{pmatrix}
\end{align*} $$
```
````


In [14]:
def cholesky(A):
    n = A.shape[0]
    L = np.zeros((n, n))   
    for j in range(n):
        sum_ = 0
        for k in range(j):
            sum_ += L[j,k] ** 2
        
        L[j,j] = np.sqrt(A[j,j] - sum_)
                
        for i in range(j+1, n):
            sum_ = 0
            for k in range(j):
                sum_ += L[i,k] * L[j,k]
            
            L[i,j] = (A[i,j] - sum_) / L[j,j]
    
    return L


A = np.array([[16, 16, 4], [16, 25, 10], [4, 10, 6]])
b = np.array([-8, -47, -30])
L = cholesky(A)
y = np.linalg.solve(L, b)
x = np.linalg.solve(L.T, y)

print(f'L = {L}')

print(f'\ny = {y}')
print(f'\nx = {x}')

L = [[4. 0. 0.]
 [4. 3. 0.]
 [1. 2. 1.]]

y = [ -2. -13.  -2.]

x = [ 3. -3. -2.]


```{exercise}
:label: ex-lu-python

Use Python or MATLAB to check your solutions to {ref}`ex-lu`, {ref}`ex-lup` and {ref}`ex-cholesky`.
```


````{exercise}
:label: ex-gramschmidt

Using pen and paper, calculate the QR decomposition using the [Gram-Schmidt process](qr-gramschmidt-section) of the following matrices:

(a) &emsp; $ \begin{pmatrix} 1 & 1 \\  -1 & 0 \end{pmatrix}$;

```{dropdown} Solution
(a) &emsp; $Q = \begin{pmatrix} \frac{\sqrt{2}}{2} & \frac{\sqrt{2}}{2} \\ - \frac{\sqrt{2}}{2} & \frac{\sqrt{2}}{2} \end{pmatrix}$, &emsp; $R = \begin{pmatrix} \sqrt{2} & \frac{\sqrt{2}}{2} \\ 0 & \frac{\sqrt{2}}{2} \end{pmatrix}$;
```

(b) &emsp; $\begin{pmatrix} 6 & 6 & 1 \\ 3 & 6 & 1 \\ 2 & 1 & 1 \end{pmatrix}$;

```{dropdown} Solution
(b) &emsp; $Q = \begin{pmatrix} \frac{6}{7} & -\frac{2}{7} & -\frac{3}{7} \\ \frac{3}{7} & \frac{6}{7} & \frac{2}{7} \\ \frac{2}{7} & -\frac{3}{7} & \frac{6}{7} \end{pmatrix}$, &emsp; $R = \begin{pmatrix} 7 & 8 & \frac{11}{7} \\ 0 & 3 & \frac{1}{7} \\ 0 & 0 & \frac{5}{7} \end{pmatrix}$;
```

(c) &emsp; $\begin{pmatrix} 1 & 2 & 1 \\ 1 & 4 & 3 \\ 1 & -4 & 6 \\ 1 & 2 & 1 \end{pmatrix}$.

```{dropdown} Solution
(c) &emsp;  $Q = \begin{pmatrix} \frac{1}{2} & \frac{1}{6} & -\frac{\sqrt{18}}{9} \\ \frac{1}{2} & \frac{1}{2} & \frac{\sqrt{18}}{6} \\ \frac{1}{2} & -\frac{5}{6} & \frac{\sqrt{18}}{18} \\ \frac{1}{2} & \frac{1}{6} & -\frac{\sqrt{18}}{9} \end{pmatrix}$ and $R = \begin{pmatrix} 2 & 2 & \frac{11}{2} \\ 0 & 6 & -\frac{19}{6} \\ 0 & 0 & \frac{11\sqrt{18}}{18} \end{pmatrix}$
```

````


````{exercise}
:label: ex-householder

Using pen and paper, calculate the QR decomposition using the [Householder transformations](qr-householder-section) of the following matrices:

(a) &emsp; $ \begin{pmatrix} 3 & 0 \\  4 & 5 \end{pmatrix}$;

```{dropdown} Solution
(a) &emsp; $Q = \begin{pmatrix} \frac{3}{5} & -\frac{4}{5} \\ \frac{4}{5} & \frac{3}{5} \end{pmatrix}$ and $R = \begin{pmatrix} 5 & 4 \\ 0 & 3 \end{pmatrix}$
```

(b) &emsp; $\begin{pmatrix} 1 & 2 & 4 \\ 0 & 0 & 5 \\ 0 & 3 & 6 \end{pmatrix}$;

```{dropdown} Solution
(b) &emsp; $Q = \begin{pmatrix} 1 & 0 & 0 \\ 0 & 0 & 1 \\ 0 & 1 & 0 \end{pmatrix}$ and $R = \begin{pmatrix} 1 & 2 & 4 \\ 0 & 3 & 6 \\ 0 & 0 & 5 \end{pmatrix}$
```
````


```{exercise}
:label: ex-qr-python

Use Python or MATLAB to check your solutions to {ref}`ex-gramschmidt` and {ref}`ex-householder`.
```

---
## Solutions

The solutions to these exercises downloaded below by right clicking on the link and select 'Save Link As':

- {Download}`Jupyter Notebook<../Python/chapter6_exercises.ipynb>`
- {Download}`MATLAB Live Script<../MATLAB/chapter6_exercises.mlx>`